/**
 * GP2.03 Gas Laws Module - Quest Data
 * 
 * Complete quest database with 60 quests:
 * - 15 BASIC quests (BASIC_GAS_LAWS stage)
 * - 20 CORE quests (IDEAL_GAS_EQUATION stage)
 * - 15 ADVANCED quests (GAS_MIXTURES stage)
 * - 10 ELITE quests (GAS_MIXTURES stage)
 */

import type { Quest, LocalizedString } from "./gp2-03-types";

// Helper function to create localized strings
const L = (en: string, cn: string = en, de: string = en): LocalizedString => ({
  en,
  cn,
  de,
});

// ============================================================================
// BASIC_GAS_LAWS Stage Quests (15 BASIC quests)
// ============================================================================

export const BASIC_GAS_LAWS_QUESTS: Quest[] = [
  // Boyle's Law Quests (5 quests)
  {
    id: "BGL-B-01",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Boyle's Law: Pressure Doubles", "波义耳定律：压力加倍", "Boyle-Gesetz: Druck verdoppelt"),
    description: L(
      "A gas occupies 2.0 L at 100 kPa. If the pressure increases to 200 kPa at constant temperature, what is the new volume?",
      "气体在100 kPa下占据2.0 L。如果在恒温下压力增加到200 kPa，新体积是多少？",
      "Ein Gas nimmt 2,0 L bei 100 kPa ein. Wenn der Druck bei konstanter Temperatur auf 200 kPa steigt, wie groß ist das neue Volumen?"
    ),
    problem: L("Calculate V_2 using Boyle's Law: P_1V_1 = P_2V_2"),
    solution: {
      type: "numerical",
      correctAnswer: 1.0,
      unit: "L",
      tolerance: 0.02,
      explanation: L(
        "Using P_1V_1 = P_2V_2: (100)(2.0) = (200)(V_2), so V_2 = 1.0 L",
        "使用 P_1V_1 = P_2V_2: (100)(2.0) = (200)(V_2)，所以 V_2 = 1.0 L",
        "Mit P_1V_1 = P_2V_2: (100)(2,0) = (200)(V_2), also V_2 = 1,0 L"
      ),
    },
    hints: [L("Pressure doubles, so volume halves")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-02",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Boyle's Law: Volume Compression"),
    description: L("A gas at 50 kPa occupies 4.0 L. What pressure is needed to compress it to 2.0 L?"),
    problem: L("Calculate P_2 using P_1V_1 = P_2V_2"),
    solution: {
      type: "numerical",
      correctAnswer: 100,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("(50)(4.0) = P_2(2.0), so P_2 = 100 kPa"),
    },
    hints: [L("Volume halves, pressure doubles")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-03",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Boyle's Law: Inverse Relationship"),
    description: L("A gas at 150 kPa and 3.0 L expands to 4.5 L. Find the new pressure."),
    problem: L("Apply P_1V_1 = P_2V_2"),
    solution: {
      type: "numerical",
      correctAnswer: 100,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("(150)(3.0) = P_2(4.5), so P_2 = 100 kPa"),
    },
    hints: [L("Volume increases by 1.5×, pressure decreases by 1.5×")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-04",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Boyle's Law: Finding Initial Volume"),
    description: L("A gas at 80 kPa is compressed to 1.5 L at 120 kPa. What was the initial volume?"),
    problem: L("Solve for V_1"),
    solution: {
      type: "numerical",
      correctAnswer: 2.25,
      unit: "L",
      tolerance: 0.02,
      explanation: L("(80)(V_1) = (120)(1.5), so V_1 = 2.25 L"),
    },
    hints: [L("Rearrange to V_1 = P_2V_2/P_1")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-05",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Boyle's Law: Constant Product"),
    description: L("For a gas at constant temperature, if PV = 600 kPa·L and P = 150 kPa, find V."),
    problem: L("Use PV = constant"),
    solution: {
      type: "numerical",
      correctAnswer: 4.0,
      unit: "L",
      tolerance: 0.02,
      explanation: L("V = 600/150 = 4.0 L"),
    },
    hints: [L("Divide constant by pressure")],
    requiredQuests: [],
  },
  // Charles's Law Quests (5 quests)
  {
    id: "BGL-B-06",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Charles's Law: Temperature Doubles"),
    description: L("A gas occupies 2.0 L at 300 K. If heated to 600 K at constant pressure, what is the new volume?"),
    problem: L("Use V_1/T_1 = V_2/T_2"),
    solution: {
      type: "numerical",
      correctAnswer: 4.0,
      unit: "L",
      tolerance: 0.02,
      explanation: L("2.0/300 = V_2/600, so V_2 = 4.0 L"),
    },
    hints: [L("Temperature doubles, volume doubles")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-07",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Charles's Law: Cooling Gas"),
    description: L("A gas at 400 K occupies 5.0 L. If cooled to 200 K, what is the new volume?"),
    problem: L("Apply Charles's Law"),
    solution: {
      type: "numerical",
      correctAnswer: 2.5,
      unit: "L",
      tolerance: 0.02,
      explanation: L("5.0/400 = V_2/200, so V_2 = 2.5 L"),
    },
    hints: [L("Temperature halves, volume halves")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-08",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Charles's Law: Finding Temperature"),
    description: L("A gas at 3.0 L and 250 K expands to 4.5 L. What is the new temperature?"),
    problem: L("Solve for T_2"),
    solution: {
      type: "numerical",
      correctAnswer: 375,
      unit: "K",
      tolerance: 0.02,
      explanation: L("3.0/250 = 4.5/T_2, so T_2 = 375 K"),
    },
    hints: [L("Volume increases by 1.5×, temperature increases by 1.5×")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-09",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Charles's Law: Celsius to Kelvin"),
    description: L("A gas at 27°C (300 K) and 2.0 L is heated to 127°C (400 K). Find the new volume."),
    problem: L("Remember to use Kelvin"),
    solution: {
      type: "numerical",
      correctAnswer: 2.67,
      unit: "L",
      tolerance: 0.02,
      explanation: L("2.0/300 = V_2/400, so V_2 = 2.67 L"),
    },
    hints: [L("Always convert to Kelvin: K = °C + 273.15")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-10",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Charles's Law: Direct Proportion"),
    description: L("At constant pressure, V/T = 0.01 L/K. If T = 350 K, find V."),
    problem: L("Use the constant ratio"),
    solution: {
      type: "numerical",
      correctAnswer: 3.5,
      unit: "L",
      tolerance: 0.02,
      explanation: L("V = 0.01 × 350 = 3.5 L"),
    },
    hints: [L("Multiply ratio by temperature")],
    requiredQuests: [],
  },
  // Avogadro's Law Quests (5 quests)
  {
    id: "BGL-B-11",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Avogadro's Law: Moles Double"),
    description: L("A gas with 1.0 mol occupies 22.4 L. If moles increase to 2.0 mol at constant T and P, find the new volume."),
    problem: L("Use V_1/n_1 = V_2/n_2"),
    solution: {
      type: "numerical",
      correctAnswer: 44.8,
      unit: "L",
      tolerance: 0.02,
      explanation: L("22.4/1.0 = V_2/2.0, so V_2 = 44.8 L"),
    },
    hints: [L("Moles double, volume doubles")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-12",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Avogadro's Law: Adding Gas"),
    description: L("A container with 0.5 mol gas at 10 L has 0.5 mol added. What is the new volume?"),
    problem: L("Total moles = 1.0 mol"),
    solution: {
      type: "numerical",
      correctAnswer: 20,
      unit: "L",
      tolerance: 0.02,
      explanation: L("10/0.5 = V_2/1.0, so V_2 = 20 L"),
    },
    hints: [L("Moles double from 0.5 to 1.0")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-13",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Avogadro's Law: Removing Gas"),
    description: L("A gas with 3.0 mol at 60 L has 1.0 mol removed. Find the new volume."),
    problem: L("Final moles = 2.0 mol"),
    solution: {
      type: "numerical",
      correctAnswer: 40,
      unit: "L",
      tolerance: 0.02,
      explanation: L("60/3.0 = V_2/2.0, so V_2 = 40 L"),
    },
    hints: [L("Moles decrease from 3.0 to 2.0")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-14",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Avogadro's Law: Molar Volume"),
    description: L("At STP, 1 mol of any ideal gas occupies 22.4 L. How many moles are in 67.2 L?"),
    problem: L("Use V_1/n_1 = V_2/n_2"),
    solution: {
      type: "numerical",
      correctAnswer: 3.0,
      unit: "mol",
      tolerance: 0.02,
      explanation: L("22.4/1.0 = 67.2/n_2, so n_2 = 3.0 mol"),
    },
    hints: [L("67.2 = 3 × 22.4")],
    requiredQuests: [],
  },
  {
    id: "BGL-B-15",
    stageId: "BASIC_GAS_LAWS",
    difficulty: "BASIC",
    title: L("Avogadro's Law: Proportionality"),
    description: L("If 0.25 mol gas occupies 5.6 L, what volume will 1.0 mol occupy?"),
    problem: L("Apply Avogadro's Law"),
    solution: {
      type: "numerical",
      correctAnswer: 22.4,
      unit: "L",
      tolerance: 0.02,
      explanation: L("5.6/0.25 = V_2/1.0, so V_2 = 22.4 L"),
    },
    hints: [L("Moles increase by 4×")],
    requiredQuests: [],
  },
];

// ============================================================================
// IDEAL_GAS_EQUATION Stage Quests (20 CORE quests)
// ============================================================================

export const IDEAL_GAS_EQUATION_QUESTS: Quest[] = [
  {
    id: "IGE-C-01",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Find Pressure"),
    description: L("Calculate pressure for 2.0 mol gas at 300 K in 0.05 m^3. Use R = 8.314 J/(mol·K)."),
    problem: L("Use PV = nRT, solve for P"),
    solution: {
      type: "numerical",
      correctAnswer: 99768,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P = nRT/V = (2.0)(8.314)(300)/0.05 = 99,768 Pa"),
    },
    hints: [L("P = nRT/V")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-02",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Find Volume"),
    description: L("Find volume for 1.0 mol at STP (101,325 Pa, 273.15 K)."),
    problem: L("Calculate V using PV = nRT"),
    solution: {
      type: "numerical",
      correctAnswer: 0.0224,
      unit: "m^3",
      tolerance: 0.02,
      explanation: L("V = nRT/P = (1.0)(8.314)(273.15)/101325 = 0.0224 m^3 = 22.4 L"),
    },
    hints: [L("This is the molar volume at STP")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-03",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Find Moles"),
    description: L("How many moles in 0.1 m^3 at 100,000 Pa and 400 K?"),
    problem: L("Solve for n"),
    solution: {
      type: "numerical",
      correctAnswer: 3.01,
      unit: "mol",
      tolerance: 0.02,
      explanation: L("n = PV/RT = (100000)(0.1)/(8.314)(400) = 3.01 mol"),
    },
    hints: [L("n = PV/RT")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-04",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Find Temperature"),
    description: L("Find temperature for 2.0 mol at 200,000 Pa in 0.02 m^3."),
    problem: L("Solve for T"),
    solution: {
      type: "numerical",
      correctAnswer: 240.6,
      unit: "K",
      tolerance: 0.02,
      explanation: L("T = PV/nR = (200000)(0.02)/(2.0)(8.314) = 240.6 K"),
    },
    hints: [L("T = PV/nR")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-05",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: High Pressure"),
    description: L("Calculate pressure for 5.0 mol at 350 K in 0.1 m^3."),
    problem: L("Use PV = nRT"),
    solution: {
      type: "numerical",
      correctAnswer: 145495,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P = (5.0)(8.314)(350)/0.1 = 145,495 Pa"),
    },
    hints: [L("Large number of moles increases pressure")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-06",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Small Volume"),
    description: L("Find pressure for 0.5 mol at 298 K in 0.01 m^3."),
    problem: L("Calculate P"),
    solution: {
      type: "numerical",
      correctAnswer: 123879,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P = (0.5)(8.314)(298)/0.01 = 123,879 Pa"),
    },
    hints: [L("Small volume increases pressure")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-07",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Large Volume"),
    description: L("Calculate volume for 2.5 mol at 50,000 Pa and 400 K."),
    problem: L("Solve for V"),
    solution: {
      type: "numerical",
      correctAnswer: 0.166,
      unit: "m^3",
      tolerance: 0.02,
      explanation: L("V = (2.5)(8.314)(400)/50000 = 0.166 m^3"),
    },
    hints: [L("Low pressure allows larger volume")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-08",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: High Temperature"),
    description: L("Find temperature for 1.0 mol at 300,000 Pa in 0.01 m^3."),
    problem: L("Calculate T"),
    solution: {
      type: "numerical",
      correctAnswer: 360.8,
      unit: "K",
      tolerance: 0.02,
      explanation: L("T = (300000)(0.01)/(1.0)(8.314) = 360.8 K"),
    },
    hints: [L("High pressure requires high temperature")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-09",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Unit Conversion"),
    description: L("Convert 0.0224 m^3 to liters. (1 m^3 = 1000 L)"),
    problem: L("Multiply by 1000"),
    solution: {
      type: "numerical",
      correctAnswer: 22.4,
      unit: "L",
      tolerance: 0.02,
      explanation: L("0.0224 m^3 × 1000 = 22.4 L"),
    },
    hints: [L("1 m^3 = 1000 L")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-10",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Pressure in atm"),
    description: L("Convert 101,325 Pa to atm. (1 atm = 101,325 Pa)"),
    problem: L("Divide by 101,325"),
    solution: {
      type: "numerical",
      correctAnswer: 1.0,
      unit: "atm",
      tolerance: 0.02,
      explanation: L("101,325 Pa / 101,325 = 1.0 atm"),
    },
    hints: [L("Standard atmospheric pressure")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-11",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Multiple Variables"),
    description: L("A gas at 150,000 Pa, 0.05 m^3, 300 K. Find moles."),
    problem: L("Use n = PV/RT"),
    solution: {
      type: "numerical",
      correctAnswer: 3.01,
      unit: "mol",
      tolerance: 0.02,
      explanation: L("n = (150000)(0.05)/(8.314)(300) = 3.01 mol"),
    },
    hints: [L("All four variables given except n")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-12",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Density Relation"),
    description: L("If P = 101,325 Pa, T = 273 K, M = 0.032 kg/mol (O_2), find density ρ = PM/RT."),
    problem: L("Calculate ρ"),
    solution: {
      type: "numerical",
      correctAnswer: 1.43,
      unit: "kg/m^3",
      tolerance: 0.02,
      explanation: L("ρ = (101325)(0.032)/(8.314)(273) = 1.43 kg/m^3"),
    },
    hints: [L("Density formula: ρ = PM/RT")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-13",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Combined Calculation"),
    description: L("Find P for 10 mol at 500 K in 0.1 m^3."),
    problem: L("Calculate pressure"),
    solution: {
      type: "numerical",
      correctAnswer: 415700,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P = (10)(8.314)(500)/0.1 = 415,700 Pa"),
    },
    hints: [L("Large moles and high temperature")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-14",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Low Temperature"),
    description: L("Find moles for gas at 10,000 Pa, 2.0 m^3, 100 K."),
    problem: L("Solve for n"),
    solution: {
      type: "numerical",
      correctAnswer: 24.06,
      unit: "mol",
      tolerance: 0.02,
      explanation: L("n = (10000)(2.0)/(8.314)(100) = 24.06 mol"),
    },
    hints: [L("Low temperature, large volume")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-15",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: High Pressure System"),
    description: L("Find volume for 0.1 mol at 1,000,000 Pa and 300 K."),
    problem: L("Calculate V"),
    solution: {
      type: "numerical",
      correctAnswer: 0.00025,
      unit: "m^3",
      tolerance: 0.02,
      explanation: L("V = (0.1)(8.314)(300)/1000000 = 0.00025 m^3"),
    },
    hints: [L("Very high pressure compresses gas")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-16",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Standard Conditions"),
    description: L("At SATP (100,000 Pa, 298 K), find volume for 1.0 mol."),
    problem: L("Use PV = nRT"),
    solution: {
      type: "numerical",
      correctAnswer: 0.0248,
      unit: "m^3",
      tolerance: 0.02,
      explanation: L("V = (1.0)(8.314)(298)/100000 = 0.0248 m^3 = 24.8 L"),
    },
    hints: [L("SATP: 25°C and 1 bar")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-17",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Proportionality"),
    description: L("If T doubles and V doubles, what happens to P? (n constant)"),
    problem: L("Analyze P = nRT/V"),
    solution: {
      type: "multiple-choice",
      correctAnswer: "unchanged",
      explanation: L("P = nRT/V. If T and V both double, P remains constant."),
    },
    hints: [L("T/V ratio stays the same")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-18",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Molar Mass"),
    description: L("If 0.032 kg gas occupies 0.0224 m^3 at STP, find molar mass M = m/n."),
    problem: L("First find n, then M"),
    solution: {
      type: "numerical",
      correctAnswer: 0.032,
      unit: "kg/mol",
      tolerance: 0.02,
      explanation: L("n = 1.0 mol at STP, so M = 0.032/1.0 = 0.032 kg/mol (O_2)"),
    },
    hints: [L("At STP, 0.0224 m^3 = 1 mol")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-19",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Work Calculation"),
    description: L("For isothermal expansion, W = nRT ln(V_2/V_1). If n=1, T=300K, V doubles, find W."),
    problem: L("Calculate work"),
    solution: {
      type: "numerical",
      correctAnswer: 1729,
      unit: "J",
      tolerance: 0.02,
      explanation: L("W = (1)(8.314)(300)ln(2) = 1729 J"),
    },
    hints: [L("ln(2) ≈ 0.693")],
    requiredQuests: [],
  },
  {
    id: "IGE-C-20",
    stageId: "IDEAL_GAS_EQUATION",
    difficulty: "CORE",
    title: L("Ideal Gas: Gas Constant"),
    description: L("What is the value of R in J/(mol·K)?"),
    problem: L("Recall the universal gas constant"),
    solution: {
      type: "numerical",
      correctAnswer: 8.314,
      unit: "J/(mol·K)",
      tolerance: 0.001,
      explanation: L("R = 8.314 J/(mol·K) is the universal gas constant"),
    },
    hints: [L("This is a fundamental constant")],
    requiredQuests: [],
  },
];

// ============================================================================
// GAS_MIXTURES Stage Quests (15 ADVANCED + 10 ELITE = 25 quests)
// ============================================================================

export const GAS_MIXTURES_QUESTS: Quest[] = [
  // ADVANCED Quests (15)
  {
    id: "GM-A-01",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Dalton's Law: Two Gases"),
    description: L("N_2 at 60 kPa and O_2 at 40 kPa are in a container. Find total pressure."),
    problem: L("Use P_total = P_1 + P_2"),
    solution: {
      type: "numerical",
      correctAnswer: 100,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P_total = 60 + 40 = 100 kPa"),
    },
    hints: [L("Dalton's Law: pressures add")],
    requiredQuests: [],
  },
  {
    id: "GM-A-02",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Partial Pressure: Mole Fraction"),
    description: L("In a mixture, N_2 has mole fraction 0.8. If total pressure is 100 kPa, find P(N_2)."),
    problem: L("Use P_i = χ_i × P_total"),
    solution: {
      type: "numerical",
      correctAnswer: 80,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P(N_2) = 0.8 × 100 = 80 kPa"),
    },
    hints: [L("Partial pressure = mole fraction × total pressure")],
    requiredQuests: [],
  },
  {
    id: "GM-A-03",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Mole Fraction: Two Components"),
    description: L("A mixture has 2 mol N_2 and 3 mol O_2. Find mole fraction of N_2."),
    problem: L("χ = n_i / n_total"),
    solution: {
      type: "numerical",
      correctAnswer: 0.4,
      tolerance: 0.02,
      explanation: L("χ(N_2) = 2/(2+3) = 0.4"),
    },
    hints: [L("Total moles = 5")],
    requiredQuests: [],
  },
  {
    id: "GM-A-04",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Three Gas Mixture"),
    description: L("He at 20 kPa, Ne at 30 kPa, Ar at 50 kPa. Find total pressure."),
    problem: L("Sum all partial pressures"),
    solution: {
      type: "numerical",
      correctAnswer: 100,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P_total = 20 + 30 + 50 = 100 kPa"),
    },
    hints: [L("Add all three pressures")],
    requiredQuests: [],
  },
  {
    id: "GM-A-05",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Finding Partial Pressure"),
    description: L("Total pressure 150 kPa. Gas A has χ = 0.6. Find P(A)."),
    problem: L("Calculate partial pressure"),
    solution: {
      type: "numerical",
      correctAnswer: 90,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P(A) = 0.6 × 150 = 90 kPa"),
    },
    hints: [L("Multiply mole fraction by total pressure")],
    requiredQuests: [],
  },
  {
    id: "GM-A-06",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Mole Fraction Sum"),
    description: L("In a mixture, χ(N_2) = 0.7, χ(O_2) = 0.2. Find χ(Ar)."),
    problem: L("Sum of mole fractions = 1"),
    solution: {
      type: "numerical",
      correctAnswer: 0.1,
      tolerance: 0.02,
      explanation: L("χ(Ar) = 1 - 0.7 - 0.2 = 0.1"),
    },
    hints: [L("All mole fractions must sum to 1.0")],
    requiredQuests: [],
  },
  {
    id: "GM-A-07",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Equal Moles Mixture"),
    description: L("A mixture has equal moles of 4 gases at 200 kPa total. Find each partial pressure."),
    problem: L("Each has χ = 0.25"),
    solution: {
      type: "numerical",
      correctAnswer: 50,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("Each: P_i = 0.25 × 200 = 50 kPa"),
    },
    hints: [L("Equal moles means equal mole fractions")],
    requiredQuests: [],
  },
  {
    id: "GM-A-08",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Finding Moles from Pressure"),
    description: L("At 100 kPa total, N_2 is 80 kPa. If total moles = 5, find moles of N_2."),
    problem: L("Use χ = P_i/P_total = n_i/n_total"),
    solution: {
      type: "numerical",
      correctAnswer: 4.0,
      unit: "mol",
      tolerance: 0.02,
      explanation: L("χ = 80/100 = 0.8, so n(N_2) = 0.8 × 5 = 4.0 mol"),
    },
    hints: [L("Mole fraction from pressure ratio")],
    requiredQuests: [],
  },
  {
    id: "GM-A-09",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Mixture Calculation"),
    description: L("1 mol He and 2 mol Ne at 300 K in 0.1 m^3. Find total pressure."),
    problem: L("Use PV = n_total RT"),
    solution: {
      type: "numerical",
      correctAnswer: 74826,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P = (3)(8.314)(300)/0.1 = 74,826 Pa"),
    },
    hints: [L("Total moles = 3")],
    requiredQuests: [],
  },
  {
    id: "GM-A-10",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Partial Pressure from Moles"),
    description: L("In previous problem, find P(He)."),
    problem: L("χ(He) = 1/3"),
    solution: {
      type: "numerical",
      correctAnswer: 24942,
      unit: "Pa",
      tolerance: 0.02,
      explanation: L("P(He) = (1/3) × 74826 = 24,942 Pa"),
    },
    hints: [L("He is 1/3 of total moles")],
    requiredQuests: ["GM-A-09"],
  },
  {
    id: "GM-A-11",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Adding Gas to Mixture"),
    description: L("A container at 100 kPa has 2 mol gas. Adding 1 mol more at constant T,V. Find new pressure."),
    problem: L("Pressure proportional to moles"),
    solution: {
      type: "numerical",
      correctAnswer: 150,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P_2 = P_1(n_2/n_1) = 100(3/2) = 150 kPa"),
    },
    hints: [L("Moles increase from 2 to 3")],
    requiredQuests: [],
  },
  {
    id: "GM-A-12",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Vapor Pressure"),
    description: L("Dry air at 100 kPa. Water vapor added with P(H_2O) = 3 kPa. Find new total pressure."),
    problem: L("Add partial pressures"),
    solution: {
      type: "numerical",
      correctAnswer: 103,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P_total = 100 + 3 = 103 kPa"),
    },
    hints: [L("Dalton's Law applies")],
    requiredQuests: [],
  },
  {
    id: "GM-A-13",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Collecting Gas Over Water"),
    description: L("Gas collected at 101 kPa total. Water vapor pressure = 3 kPa. Find gas pressure."),
    problem: L("P(gas) = P_total - P(H_2O)"),
    solution: {
      type: "numerical",
      correctAnswer: 98,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P(gas) = 101 - 3 = 98 kPa"),
    },
    hints: [L("Subtract water vapor pressure")],
    requiredQuests: [],
  },
  {
    id: "GM-A-14",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Mole Fraction Validation"),
    description: L("A mixture has χ_1 = 0.4, χ_2 = 0.35, χ_3 = 0.25. Is this valid?"),
    problem: L("Check if sum = 1.0"),
    solution: {
      type: "multiple-choice",
      correctAnswer: "yes",
      explanation: L("0.4 + 0.35 + 0.25 = 1.0, so valid"),
    },
    hints: [L("Sum must equal 1.0 within tolerance")],
    requiredQuests: [],
  },
  {
    id: "GM-A-15",
    stageId: "GAS_MIXTURES",
    difficulty: "ADVANCED",
    title: L("Average Molar Mass"),
    description: L("Air: 80% N_2 (M=28 g/mol), 20% O_2 (M=32 g/mol). Find average M."),
    problem: L("M_avg = Σ(χ_i × M_i)"),
    solution: {
      type: "numerical",
      correctAnswer: 28.8,
      unit: "g/mol",
      tolerance: 0.02,
      explanation: L("M = 0.8(28) + 0.2(32) = 28.8 g/mol"),
    },
    hints: [L("Weighted average by mole fraction")],
    requiredQuests: [],
  },
  // ELITE Quests (10)
  {
    id: "GM-E-01",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Complex Mixture"),
    description: L("5 gases with equal moles at 500 kPa total. One gas removed. Find new total pressure."),
    problem: L("4/5 of original pressure"),
    solution: {
      type: "numerical",
      correctAnswer: 400,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P_new = (4/5) × 500 = 400 kPa"),
    },
    hints: [L("Pressure proportional to moles")],
    requiredQuests: [],
  },
  {
    id: "GM-E-02",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Diffusion Rate"),
    description: L("Graham's Law: rate_1/rate_2 = √(M_2/M_1). If M_1=4, M_2=16, find rate ratio."),
    problem: L("Calculate rate_1/rate_2"),
    solution: {
      type: "numerical",
      correctAnswer: 2.0,
      tolerance: 0.02,
      explanation: L("rate_1/rate_2 = √(16/4) = 2.0"),
    },
    hints: [L("Lighter gas diffuses faster")],
    requiredQuests: [],
  },
  {
    id: "GM-E-03",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Real Gas Deviation"),
    description: L("At very high pressure, real gases deviate from ideal. Which factor dominates?"),
    problem: L("Molecular volume or intermolecular forces?"),
    solution: {
      type: "multiple-choice",
      correctAnswer: "volume",
      explanation: L("At high P, molecular volume becomes significant"),
    },
    hints: [L("Molecules take up space")],
    requiredQuests: [],
  },
  {
    id: "GM-E-04",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Compressibility Factor"),
    description: L("Z = PV/nRT. For ideal gas, Z = ?"),
    problem: L("Calculate Z for ideal behavior"),
    solution: {
      type: "numerical",
      correctAnswer: 1.0,
      tolerance: 0.001,
      explanation: L("For ideal gas, PV = nRT, so Z = 1.0"),
    },
    hints: [L("Ideal gas follows PV = nRT exactly")],
    requiredQuests: [],
  },
  {
    id: "GM-E-05",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Van der Waals Equation"),
    description: L("(P + a/V^2)(V - b) = RT for 1 mol. What do 'a' and 'b' represent?"),
    problem: L("Identify correction terms"),
    solution: {
      type: "multiple-choice",
      correctAnswer: "forces_and_volume",
      explanation: L("'a' corrects for intermolecular forces, 'b' for molecular volume"),
    },
    hints: [L("Real gas corrections")],
    requiredQuests: [],
  },
  {
    id: "GM-E-06",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Partial Pressure in Reaction"),
    description: L("2H_2 + O_2 → 2H_2O. Start: 2 mol H_2, 1 mol O_2 at 300 kPa. After reaction, find P(H_2O)."),
    problem: L("All reactants consumed, 2 mol H_2O formed"),
    solution: {
      type: "numerical",
      correctAnswer: 200,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("2 mol H_2O from 3 mol total: P = (2/3) × 300 = 200 kPa"),
    },
    hints: [L("Stoichiometry determines moles")],
    requiredQuests: [],
  },
  {
    id: "GM-E-07",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Humidity Calculation"),
    description: L("Relative humidity = (P_actual/P_sat) × 100%. If P_sat = 3 kPa, P_actual = 2 kPa, find RH."),
    problem: L("Calculate percentage"),
    solution: {
      type: "numerical",
      correctAnswer: 66.7,
      unit: "%",
      tolerance: 0.02,
      explanation: L("RH = (2/3) × 100 = 66.7%"),
    },
    hints: [L("Ratio of actual to saturated vapor pressure")],
    requiredQuests: [],
  },
  {
    id: "GM-E-08",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Effusion Time"),
    description: L("Gas A (M=4) effuses in 10 s. How long for gas B (M=16)?"),
    problem: L("Use Graham's Law: t_2/t_1 = √(M_2/M_1)"),
    solution: {
      type: "numerical",
      correctAnswer: 20,
      unit: "s",
      tolerance: 0.02,
      explanation: L("t_2 = 10 × √(16/4) = 20 s"),
    },
    hints: [L("Heavier gas takes longer")],
    requiredQuests: [],
  },
  {
    id: "GM-E-09",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Kinetic Energy Distribution"),
    description: L("In a mixture at thermal equilibrium, all gases have the same average..."),
    problem: L("What property is equal?"),
    solution: {
      type: "multiple-choice",
      correctAnswer: "kinetic_energy",
      explanation: L("All gases at same T have same average kinetic energy"),
    },
    hints: [L("Temperature measures kinetic energy")],
    requiredQuests: [],
  },
  {
    id: "GM-E-10",
    stageId: "GAS_MIXTURES",
    difficulty: "ELITE",
    title: L("Basel Air Quality"),
    description: L("Basel air: N_2 78%, O_2 21%, Ar 1% at 101 kPa. Find P(O_2)."),
    problem: L("Calculate partial pressure of oxygen"),
    solution: {
      type: "numerical",
      correctAnswer: 21.2,
      unit: "kPa",
      tolerance: 0.02,
      explanation: L("P(O_2) = 0.21 × 101 = 21.2 kPa"),
    },
    hints: [L("Basel-specific application of Dalton's Law")],
    requiredQuests: [],
  },
];

// ============================================================================
// Export All Quests
// ============================================================================

export const ALL_QUESTS: Quest[] = [
  ...BASIC_GAS_LAWS_QUESTS,
  ...IDEAL_GAS_EQUATION_QUESTS,
  ...GAS_MIXTURES_QUESTS,
];

// Verify quest count
if (ALL_QUESTS.length !== 60) {
  console.warn(`Expected 60 quests, got ${ALL_QUESTS.length}`);
}
