/**
 * SM2.09 Inequalities Module - Basel-Specific Scenarios
 * Four scenarios (150-250 words each) in EN/CN/DE
 */

export interface BaselScenario {
    id: string;
    en: string;
    cn: string;
    de: string;
}

export const baselScenarios: Record<string, BaselScenario> = {
    tram_ticket: {
        id: "tram_ticket",
        en: `Basel's public transport system (BVB/BLT) offers various ticket options for daily commuters. A single ticket costs CHF 3.80, while a day pass costs CHF 9.00. You're planning your daily commute and want to determine when buying a day pass becomes more economical than buying individual tickets. Let x represent the number of tram rides you take in a day. The cost of individual tickets is 3.80x CHF, while the day pass costs a flat 9.00 CHF. To find when the day pass is cheaper, we need to solve the inequality: 3.80x > 9.00. This inequality helps you make an informed decision about which ticket option saves you money based on your travel patterns. Understanding inequalities in this context demonstrates how mathematics applies to everyday financial decisions in Basel's public transport system. The solution shows that if you take more than 2.37 rides per day (meaning 3 or more rides), the day pass becomes the better value. This practical application of inequalities helps Basel residents optimize their transportation budget while navigating the city's efficient tram network.`,
        cn: `巴塞尔的公共交通系统（BVB/BLT）为日常通勤者提供多种票务选择。单程票价为 3.80 瑞士法郎，而日票价格为 9.00 瑞士法郎。您正在规划每日通勤，想要确定何时购买日票比购买单程票更经济。设 x 表示您一天内乘坐电车的次数。单程票的总成本为 3.80x 瑞士法郎，而日票的固定价格为 9.00 瑞士法郎。要找出何时日票更便宜，我们需要解不等式：3.80x > 9.00。这个不等式帮助您根据出行模式做出明智的票务选择决策。在这种情况下理解不等式展示了数学如何应用于巴塞尔公共交通系统中的日常财务决策。解决方案表明，如果您每天乘坐超过 2.37 次（即 3 次或更多），日票就变得更有价值。不等式的这种实际应用帮助巴塞尔居民在使用城市高效电车网络时优化交通预算。`,
        de: `Das öffentliche Verkehrssystem von Basel (BVB/BLT) bietet verschiedene Ticketoptionen für Pendler. Ein Einzelticket kostet CHF 3.80, während eine Tageskarte CHF 9.00 kostet. Sie planen Ihren täglichen Arbeitsweg und möchten bestimmen, wann der Kauf einer Tageskarte wirtschaftlicher ist als der Kauf von Einzeltickets. Sei x die Anzahl der Tramfahrten, die Sie an einem Tag unternehmen. Die Kosten für Einzeltickets betragen 3.80x CHF, während die Tageskarte pauschal 9.00 CHF kostet. Um herauszufinden, wann die Tageskarte günstiger ist, müssen wir die Ungleichung lösen: 3.80x > 9.00. Diese Ungleichung hilft Ihnen, eine fundierte Entscheidung darüber zu treffen, welche Ticketoption Ihnen Geld spart, basierend auf Ihren Reisemustern. Das Verständnis von Ungleichungen in diesem Kontext zeigt, wie Mathematik auf alltägliche finanzielle Entscheidungen im Basler Verkehrssystem angewendet wird. Die Lösung zeigt, dass die Tageskarte bei mehr als 2.37 Fahrten pro Tag (also 3 oder mehr Fahrten) den besseren Wert bietet. Diese praktische Anwendung von Ungleichungen hilft Basler Einwohnern, ihr Transportbudget zu optimieren.`
    },
    
    roche_dosage: {
        id: "roche_dosage",
        en: `Roche, one of Basel's largest employers and a global pharmaceutical leader, develops medications that require precise dosing guidelines to ensure both safety and effectiveness. Consider a medication where the therapeutic dose must be between 50mg and 200mg per day to be effective while remaining safe for patients. The dosage depends on the patient's body weight. For a patient weighing w kilograms, the recommended dose is 2.5w mg per day. To ensure the dose falls within the safe and effective range, we need to solve the compound inequality: 50 ≤ 2.5w ≤ 200. This translates to determining the range of patient weights for which this dosing formula is appropriate. Solving this system of inequalities gives us: 20 ≤ w ≤ 80, meaning the formula is suitable for patients weighing between 20 and 80 kilograms. This example illustrates how pharmaceutical companies like Roche use mathematical inequalities to establish safe dosing guidelines, ensuring patient safety while maintaining therapeutic effectiveness. Understanding compound inequalities is essential in pharmaceutical research and clinical practice.`,
        cn: `罗氏制药是巴塞尔最大的雇主之一，也是全球制药领导者，开发需要精确剂量指南的药物以确保安全性和有效性。考虑一种药物，其治疗剂量必须在每天 50 毫克至 200 毫克之间才能有效且对患者安全。剂量取决于患者的体重。对于体重为 w 公斤的患者，推荐剂量为每天 2.5w 毫克。为确保剂量在安全有效范围内，我们需要解复合不等式：50 ≤ 2.5w ≤ 200。这转化为确定该剂量公式适用的患者体重范围。解这个不等式系统得到：20 ≤ w ≤ 80，意味着该公式适用于体重在 20 至 80 公斤之间的患者。这个例子说明了像罗氏这样的制药公司如何使用数学不等式来建立安全的剂量指南，在保持治疗效果的同时确保患者安全。理解复合不等式在制药研究和临床实践中至关重要。`,
        de: `Roche, einer der größten Arbeitgeber Basels und ein globaler Pharmaführer, entwickelt Medikamente, die präzise Dosierungsrichtlinien erfordern, um sowohl Sicherheit als auch Wirksamkeit zu gewährleisten. Betrachten Sie ein Medikament, bei dem die therapeutische Dosis zwischen 50 mg und 200 mg pro Tag liegen muss, um wirksam und gleichzeitig sicher für Patienten zu sein. Die Dosierung hängt vom Körpergewicht des Patienten ab. Für einen Patienten mit einem Gewicht von w Kilogramm beträgt die empfohlene Dosis 2.5w mg pro Tag. Um sicherzustellen, dass die Dosis im sicheren und wirksamen Bereich liegt, müssen wir die zusammengesetzte Ungleichung lösen: 50 ≤ 2.5w ≤ 200. Dies bedeutet, den Gewichtsbereich der Patienten zu bestimmen, für die diese Dosierungsformel geeignet ist. Die Lösung dieses Ungleichungssystems ergibt: 20 ≤ w ≤ 80, was bedeutet, dass die Formel für Patienten mit einem Gewicht zwischen 20 und 80 Kilogramm geeignet ist. Dieses Beispiel veranschaulicht, wie Pharmaunternehmen wie Roche mathematische Ungleichungen verwenden, um sichere Dosierungsrichtlinien festzulegen.`
    },
    
    basel_marathon: {
        id: "basel_marathon",
        en: `The Basel Marathon (Basel Stadt Lauf) is one of Switzerland's premier running events, attracting thousands of participants each year. The marathon has different qualification standards for various age categories to ensure fair competition. To qualify for the elite wave start, runners must have completed a previous marathon within specific time limits based on their age group. For the men's elite category (ages 18-39), the qualification time is under 3 hours 15 minutes (195 minutes). For ages 40-49, the time extends to under 3 hours 30 minutes (210 minutes). Let t represent your marathon time in minutes, and let a represent your age. The qualification criteria can be expressed as a system of inequalities: If 18 ≤ a ≤ 39, then t < 195; If 40 ≤ a ≤ 49, then t < 210. These compound inequalities help runners determine whether they qualify for elite wave placement. Understanding how to work with systems of inequalities is essential for interpreting qualification standards in competitive sports events like the Basel Marathon.`,
        cn: `巴塞尔马拉松（Basel Stadt Lauf）是瑞士顶级跑步赛事之一，每年吸引数千名参与者。马拉松针对不同年龄类别设有不同的资格标准以确保公平竞争。要获得精英组起跑资格，跑者必须在之前的马拉松比赛中根据年龄组在特定时间限制内完成比赛。对于男子精英组（18-39 岁），资格时间为 3 小时 15 分钟（195 分钟）以内。对于 40-49 岁年龄组，时间延长至 3 小时 30 分钟（210 分钟）以内。设 t 表示您的马拉松时间（分钟），a 表示您的年龄。资格标准可以表示为不等式系统：如果 18 ≤ a ≤ 39，则 t < 195；如果 40 ≤ a ≤ 49，则 t < 210。这些复合不等式帮助跑者确定他们是否有资格参加精英组起跑。理解如何处理不等式系统对于解释像巴塞尔马拉松这样的竞技体育赛事的资格标准至关重要。`,
        de: `Der Basel Marathon (Basel Stadt Lauf) ist eines der führenden Laufevents der Schweiz und zieht jedes Jahr Tausende von Teilnehmern an. Der Marathon hat unterschiedliche Qualifikationsstandards für verschiedene Alterskategorien, um einen fairen Wettbewerb zu gewährleisten. Um sich für den Elite-Wellenstart zu qualifizieren, müssen Läufer einen vorherigen Marathon innerhalb bestimmter Zeitlimits basierend auf ihrer Altersgruppe absolviert haben. Für die Männer-Elite-Kategorie (18-39 Jahre) beträgt die Qualifikationszeit unter 3 Stunden 15 Minuten (195 Minuten). Für die Altersgruppe 40-49 Jahre verlängert sich die Zeit auf unter 3 Stunden 30 Minuten (210 Minuten). Sei t Ihre Marathonzeit in Minuten und a Ihr Alter. Die Qualifikationskriterien können als System von Ungleichungen ausgedrückt werden: Wenn 18 ≤ a ≤ 39, dann t < 195; Wenn 40 ≤ a ≤ 49, dann t < 210. Diese zusammengesetzten Ungleichungen helfen Läufern zu bestimmen, ob sie sich für die Elite-Wellenplatzierung qualifizieren.`
    },
    
    university_basel: {
        id: "university_basel",
        en: `The University of Basel, founded in 1460, is Switzerland's oldest university and uses a points-based admission system for competitive programs like Medicine and Psychology. Applicants are evaluated on multiple criteria: Matura grade (maximum 6.0 points), entrance exam score (maximum 100 points), and interview performance (maximum 20 points). For the Medicine program, the total score S must satisfy: S ≥ 110 points for guaranteed admission. Additionally, no single component can fall below minimum thresholds: Matura grade M ≥ 5.0, entrance exam E ≥ 60, and interview I ≥ 12. The total score is calculated as: S = 10M + E + I. To determine if you qualify for guaranteed admission, you must solve the system of inequalities: 10M + E + I ≥ 110, M ≥ 5.0, E ≥ 60, and I ≥ 12. This system of inequalities helps prospective students understand the minimum requirements across all evaluation criteria. It demonstrates how universities use mathematical inequalities to establish fair and transparent admission standards for competitive academic programs.`,
        cn: `巴塞尔大学成立于 1460 年，是瑞士最古老的大学，对医学和心理学等竞争性专业采用基于积分的录取系统。申请者根据多个标准进行评估：高中毕业成绩（最高 6.0 分）、入学考试成绩（最高 100 分）和面试表现（最高 20 分）。对于医学专业，总分 S 必须满足：S ≥ 110 分才能保证录取。此外，任何单项都不能低于最低门槛：高中毕业成绩 M ≥ 5.0，入学考试 E ≥ 60，面试 I ≥ 12。总分计算公式为：S = 10M + E + I。要确定您是否有资格保证录取，您必须解不等式系统：10M + E + I ≥ 110，M ≥ 5.0，E ≥ 60，I ≥ 12。这个不等式系统帮助未来的学生理解所有评估标准的最低要求。它展示了大学如何使用数学不等式为竞争性学术项目建立公平透明的录取标准。`,
        de: `Die Universität Basel, gegründet 1460, ist die älteste Universität der Schweiz und verwendet ein punktebasiertes Zulassungssystem für wettbewerbsintensive Programme wie Medizin und Psychologie. Bewerber werden nach mehreren Kriterien bewertet: Matura-Note (maximal 6.0 Punkte), Aufnahmeprüfungsergebnis (maximal 100 Punkte) und Interviewleistung (maximal 20 Punkte). Für das Medizinstudium muss die Gesamtpunktzahl S erfüllen: S ≥ 110 Punkte für garantierte Zulassung. Zusätzlich darf keine einzelne Komponente unter Mindestschwellen fallen: Matura-Note M ≥ 5.0, Aufnahmeprüfung E ≥ 60 und Interview I ≥ 12. Die Gesamtpunktzahl wird berechnet als: S = 10M + E + I. Um festzustellen, ob Sie sich für eine garantierte Zulassung qualifizieren, müssen Sie das Ungleichungssystem lösen: 10M + E + I ≥ 110, M ≥ 5.0, E ≥ 60 und I ≥ 12. Dieses Ungleichungssystem hilft zukünftigen Studenten, die Mindestanforderungen über alle Bewertungskriterien hinweg zu verstehen.`
    }
};
