"use client";

import { useEffect, useCallback } from "react";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";
import { useAppStore } from "@/lib/store";
import { translations } from "@/lib/i18n";
import ChamberLayout from "@/components/layout/ChamberLayout";
import ProbabilityVisualizer from "@/components/chamber/sm2-08/ProbabilityVisualizer";
import { Difficulty, Quest, useQuestManager } from "@/hooks/useQuestManager";

type Stage = "BASIC_PROB" | "LOTTERY" | "COMBINED" | "DATA_STATS";
type ProbQuest = Quest & { stage: Stage; context?: string; scenario?: string };

export default function SM208Page() {
  const { currentLanguage, completeStage } = useAppStore();
  const locale = translations[currentLanguage as keyof typeof translations] as typeof translations.EN;
  const t = locale.sm2_08 || translations.EN.sm2_08;

  const buildStagePool = useCallback((t: typeof translations.EN.sm2_08, difficulty: Difficulty, stage: Stage): ProbQuest[] => {
    const pools: Record<Stage, Record<Difficulty, ProbQuest[]>> = {
      BASIC_PROB: {
        BASIC: [
          {
            id: "B1",
            difficulty,
            stage,
            scenario: t.scenarios.bus_punctuality,
            context: t.problems.bus_ontime_16_20,
            promptLatex: "P(\\text{on time})",
            expressionLatex: "\\frac{16}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.8, unit: "" }],
            correctLatex: "P = \\frac{16}{20} = 0.8 = 80\\%",
          },
          {
            id: "B2",
            difficulty,
            stage,
            scenario: t.scenarios.weather_basel,
            context: t.problems.weather_rain_12_30,
            promptLatex: "P(\\text{rain})",
            expressionLatex: "\\frac{12}{30}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.4, unit: "" }],
            correctLatex: "P = \\frac{12}{30} = 0.4 = 40\\%",
          },
          {
            id: "B3",
            difficulty,
            stage,
            scenario: t.scenarios.dice_game,
            context: t.problems.dice_roll_3,
            promptLatex: "P(3)",
            expressionLatex: "\\frac{1}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\frac{1}{6} \\approx 0.167",
          },
          {
            id: "B4",
            difficulty,
            stage,
            scenario: t.scenarios.coin_flip,
            context: t.problems.coin_heads,
            promptLatex: "P(\\text{heads})",
            expressionLatex: "\\frac{1}{2}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\frac{1}{2} = 0.5 = 50\\%",
          },
          {
            id: "B5",
            difficulty,
            stage,
            scenario: t.scenarios.bus_punctuality,
            context: t.problems.bus_ontime_18_20,
            promptLatex: "P(\\text{on time})",
            expressionLatex: "\\frac{18}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.9, unit: "" }],
            correctLatex: "P = \\frac{18}{20} = 0.9 = 90\\%",
          },
        ],
        CORE: [
          {
            id: "C1",
            difficulty,
            stage,
            scenario: t.scenarios.school_cafeteria,
            context: t.problems.cafeteria_pizza,
            promptLatex: "P(\\text{pizza})",
            expressionLatex: "\\frac{3}{5}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.6, unit: "" }],
            correctLatex: "P = \\frac{3}{5} = 0.6 = 60\\%",
          },
          {
            id: "C2",
            difficulty,
            stage,
            scenario: t.scenarios.exam_results,
            context: t.problems.exam_pass,
            promptLatex: "P(\\text{pass})",
            expressionLatex: "\\frac{85}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.85, unit: "" }],
            correctLatex: "P = 0.85 = 85\\%",
          },
          {
            id: "C3",
            difficulty,
            stage,
            scenario: t.scenarios.weather_basel,
            context: t.problems.weather_sunny_21_30,
            promptLatex: "P(\\text{sunny})",
            expressionLatex: "\\frac{21}{30}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.7, unit: "" }],
            correctLatex: "P = \\frac{21}{30} = 0.7 = 70\\%",
          },
          {
            id: "C4",
            difficulty,
            stage,
            scenario: t.scenarios.tram_punctuality,
            context: t.problems.tram_ontime_17_20,
            promptLatex: "P(\\text{on time})",
            expressionLatex: "\\frac{17}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.85, unit: "" }],
            correctLatex: "P = \\frac{17}{20} = 0.85 = 85\\%",
          },
          {
            id: "C5",
            difficulty,
            stage,
            scenario: t.scenarios.dice_game,
            context: t.problems.dice_greater_4,
            promptLatex: "P(>4)",
            expressionLatex: "\\frac{2}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.333, unit: "" }],
            correctLatex: "P = \\frac{2}{6} \\approx 0.333",
          },
        ],
        ADVANCED: [
          {
            id: "A1",
            difficulty,
            stage,
            scenario: t.scenarios.dice_game,
            context: t.problems.dice_even,
            promptLatex: "P(\\text{even})",
            expressionLatex: "\\frac{3}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\frac{3}{6} = 0.5 = 50\\%",
          },
          {
            id: "A2",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_heart,
            promptLatex: "P(\\text{heart})",
            expressionLatex: "\\frac{13}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\frac{13}{52} = 0.25 = 25\\%",
          },
          {
            id: "A3",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_red,
            promptLatex: "P(\\text{red})",
            expressionLatex: "\\frac{26}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\frac{26}{52} = 0.5 = 50\\%",
          },
          {
            id: "A4",
            difficulty,
            stage,
            scenario: t.scenarios.dice_two,
            context: t.problems.two_dice_sum_8,
            promptLatex: "P(\\text{sum}=8)",
            expressionLatex: "\\frac{5}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.139, unit: "" }],
            correctLatex: "P = \\frac{5}{36} \\approx 0.139",
          },
          {
            id: "A5",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_face,
            promptLatex: "P(\\text{face})",
            expressionLatex: "\\frac{12}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.231, unit: "" }],
            correctLatex: "P = \\frac{12}{52} \\approx 0.231",
          },
        ],
        ELITE: [
          {
            id: "E1",
            difficulty,
            stage,
            scenario: t.scenarios.dice_advanced,
            context: t.problems.dice_prime,
            promptLatex: "P(\\text{prime})",
            expressionLatex: "\\frac{3}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\frac{3}{6} = 0.5 = 50\\%",
          },
          {
            id: "E2",
            difficulty,
            stage,
            scenario: t.scenarios.dice_two,
            context: t.problems.two_dice_sum_10,
            promptLatex: "P(\\text{sum}=10)",
            expressionLatex: "\\frac{3}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.083, unit: "" }],
            correctLatex: "P = \\frac{3}{36} \\approx 0.083",
          },
          {
            id: "E3",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_ace_or_king,
            promptLatex: "P(\\text{A or K})",
            expressionLatex: "\\frac{8}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.154, unit: "" }],
            correctLatex: "P = \\frac{8}{52} \\approx 0.154",
          },
          {
            id: "E4",
            difficulty,
            stage,
            scenario: t.scenarios.dice_two,
            context: t.problems.two_dice_doubles,
            promptLatex: "P(\\text{doubles})",
            expressionLatex: "\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\frac{6}{36} \\approx 0.167",
          },
          {
            id: "E5",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_spade_face,
            promptLatex: "P(\\text{spade face})",
            expressionLatex: "\\frac{3}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.058, unit: "" }],
            correctLatex: "P = \\frac{3}{52} \\approx 0.058",
          },
        ],
      },
      LOTTERY: {
        BASIC: [
          {
            id: "L1",
            difficulty,
            stage,
            scenario: t.scenarios.school_raffle,
            context: t.problems.school_raffle_win,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{3}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.03, unit: "" }],
            correctLatex: "P = \\frac{3}{100} = 0.03 = 3\\%",
          },
          {
            id: "L2",
            difficulty,
            stage,
            scenario: t.scenarios.school_raffle,
            context: t.problems.school_raffle_5_tickets,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{5}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.05, unit: "" }],
            correctLatex: "P = \\frac{5}{100} = 0.05 = 5\\%",
          },
          {
            id: "L3",
            difficulty,
            stage,
            scenario: t.scenarios.coin_flip,
            context: t.problems.coin_two_heads,
            promptLatex: "P(\\text{2 heads})",
            expressionLatex: "\\frac{1}{4}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\frac{1}{4} = 0.25 = 25\\%",
          },
          {
            id: "L4",
            difficulty,
            stage,
            scenario: t.scenarios.dice_game,
            context: t.problems.dice_not_six,
            promptLatex: "P(\\text{not 6})",
            expressionLatex: "\\frac{5}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.833, unit: "" }],
            correctLatex: "P = \\frac{5}{6} \\approx 0.833",
          },
          {
            id: "L5",
            difficulty,
            stage,
            scenario: t.scenarios.school_raffle,
            context: t.problems.school_raffle_2_tickets,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{2}{50}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.04, unit: "" }],
            correctLatex: "P = \\frac{2}{50} = 0.04 = 4\\%",
          },
        ],
        CORE: [
          {
            id: "L6",
            difficulty,
            stage,
            scenario: t.scenarios.fasnacht_game,
            context: t.problems.dice_sum_7,
            promptLatex: "P(\\text{sum}=7)",
            expressionLatex: "\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\frac{6}{36} \\approx 0.167 = 16.7\\%",
          },
          {
            id: "L7",
            difficulty,
            stage,
            scenario: t.scenarios.fasnacht_game,
            context: t.problems.dice_sum_9,
            promptLatex: "P(\\text{sum}=9)",
            expressionLatex: "\\frac{4}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.111, unit: "" }],
            correctLatex: "P = \\frac{4}{36} \\approx 0.111",
          },
          {
            id: "L8",
            difficulty,
            stage,
            scenario: t.scenarios.coin_flip,
            context: t.problems.coin_three_all_heads,
            promptLatex: "P(\\text{3 heads})",
            expressionLatex: "\\frac{1}{8}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.125, unit: "" }],
            correctLatex: "P = \\frac{1}{8} = 0.125",
          },
          {
            id: "L9",
            difficulty,
            stage,
            scenario: t.scenarios.fasnacht_game,
            context: t.problems.dice_sum_6,
            promptLatex: "P(\\text{sum}=6)",
            expressionLatex: "\\frac{5}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.139, unit: "" }],
            correctLatex: "P = \\frac{5}{36} \\approx 0.139",
          },
          {
            id: "L10",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_two_red,
            promptLatex: "P(\\text{2 red})",
            expressionLatex: "\\frac{26}{52} \\times \\frac{25}{51}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.245, unit: "" }],
            correctLatex: "P \\approx 0.245",
          },
        ],
        ADVANCED: [
          {
            id: "L11",
            difficulty,
            stage,
            scenario: t.scenarios.swiss_lotto_simple,
            context: t.problems.lotto_simple,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{1}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.05, unit: "" }],
            correctLatex: "P = \\frac{1}{20} = 0.05 = 5\\%",
          },
          {
            id: "L12",
            difficulty,
            stage,
            scenario: t.scenarios.swiss_lotto_simple,
            context: t.problems.lotto_4_from_8,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{1}{70}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.014, unit: "" }],
            correctLatex: "P = \\frac{1}{70} \\approx 0.014",
          },
          {
            id: "L13",
            difficulty,
            stage,
            scenario: t.scenarios.fasnacht_game,
            context: t.problems.dice_sum_less_5,
            promptLatex: "P(\\text{sum}<5)",
            expressionLatex: "\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\frac{6}{36} \\approx 0.167",
          },
          {
            id: "L14",
            difficulty,
            stage,
            scenario: t.scenarios.coin_flip,
            context: t.problems.coin_four_at_least_3_heads,
            promptLatex: "P(\\geq 3 \\text{ heads})",
            expressionLatex: "\\frac{5}{16}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.313, unit: "" }],
            correctLatex: "P = \\frac{5}{16} \\approx 0.313",
          },
          {
            id: "L15",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_three_hearts,
            promptLatex: "P(\\text{3 hearts})",
            expressionLatex: "\\frac{13}{52} \\times \\frac{12}{51} \\times \\frac{11}{50}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.013, unit: "" }],
            correctLatex: "P \\approx 0.013",
          },
        ],
        ELITE: [
          {
            id: "L16",
            difficulty,
            stage,
            scenario: t.scenarios.dice_win_condition,
            context: t.problems.dice_sum_7_or_11,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{8}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.222, unit: "" }],
            correctLatex: "P = \\frac{8}{36} \\approx 0.222 = 22.2\\%",
          },
          {
            id: "L17",
            difficulty,
            stage,
            scenario: t.scenarios.dice_win_condition,
            context: t.problems.dice_sum_2_3_12,
            promptLatex: "P(\\text{lose})",
            expressionLatex: "\\frac{4}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.111, unit: "" }],
            correctLatex: "P = \\frac{4}{36} \\approx 0.111",
          },
          {
            id: "L18",
            difficulty,
            stage,
            scenario: t.scenarios.swiss_lotto_simple,
            context: t.problems.lotto_5_from_10,
            promptLatex: "P(\\text{win})",
            expressionLatex: "\\frac{1}{252}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.004, unit: "" }],
            correctLatex: "P = \\frac{1}{252} \\approx 0.004",
          },
          {
            id: "L19",
            difficulty,
            stage,
            scenario: t.scenarios.coin_flip,
            context: t.problems.coin_five_exactly_2_heads,
            promptLatex: "P(\\text{exactly 2})",
            expressionLatex: "\\frac{10}{32}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.313, unit: "" }],
            correctLatex: "P = \\frac{10}{32} \\approx 0.313",
          },
          {
            id: "L20",
            difficulty,
            stage,
            scenario: t.scenarios.card_game,
            context: t.problems.card_poker_pair,
            promptLatex: "P(\\text{pair})",
            expressionLatex: "\\text{complex}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.423, unit: "" }],
            correctLatex: "P \\approx 0.423",
          },
        ],
      },
      COMBINED: {
        BASIC: [
          {
            id: "CB1",
            difficulty,
            stage,
            scenario: t.scenarios.two_buses,
            context: t.problems.two_buses_ontime,
            promptLatex: "P(\\text{both on time})",
            expressionLatex: "0.8 \\times 0.7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.56, unit: "" }],
            correctLatex: "P = 0.8 \\times 0.7 = 0.56 = 56\\%",
          },
          {
            id: "CB2",
            difficulty,
            stage,
            scenario: t.scenarios.two_coins,
            context: t.problems.two_coins_both_heads,
            promptLatex: "P(\\text{both heads})",
            expressionLatex: "0.5 \\times 0.5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = 0.5 \\times 0.5 = 0.25",
          },
          {
            id: "CB3",
            difficulty,
            stage,
            scenario: t.scenarios.two_dice,
            context: t.problems.two_dice_both_even,
            promptLatex: "P(\\text{both even})",
            expressionLatex: "0.5 \\times 0.5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = 0.5 \\times 0.5 = 0.25",
          },
          {
            id: "CB4",
            difficulty,
            stage,
            scenario: t.scenarios.weather_basel,
            context: t.problems.two_days_both_sunny,
            promptLatex: "P(\\text{both sunny})",
            expressionLatex: "0.7 \\times 0.7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.49, unit: "" }],
            correctLatex: "P = 0.7 \\times 0.7 = 0.49",
          },
          {
            id: "CB5",
            difficulty,
            stage,
            scenario: t.scenarios.exam_results,
            context: t.problems.two_students_both_pass,
            promptLatex: "P(\\text{both pass})",
            expressionLatex: "0.85 \\times 0.85",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.723, unit: "" }],
            correctLatex: "P = 0.85 \\times 0.85 \\approx 0.723",
          },
        ],
        CORE: [
          {
            id: "CC1",
            difficulty,
            stage,
            scenario: t.scenarios.fc_basel,
            context: t.problems.fc_basel_wins,
            promptLatex: "P(\\text{both win})",
            expressionLatex: "0.6 \\times 0.3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.18, unit: "" }],
            correctLatex: "P = 0.6 \\times 0.3 = 0.18 = 18\\%",
          },
          {
            id: "CC2",
            difficulty,
            stage,
            scenario: t.scenarios.three_buses,
            context: t.problems.three_buses_all_ontime,
            promptLatex: "P(\\text{all on time})",
            expressionLatex: "0.8 \\times 0.75 \\times 0.9",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.54, unit: "" }],
            correctLatex: "P = 0.8 \\times 0.75 \\times 0.9 = 0.54",
          },
          {
            id: "CC3",
            difficulty,
            stage,
            scenario: t.scenarios.weather_basel,
            context: t.problems.three_days_all_sunny,
            promptLatex: "P(\\text{all sunny})",
            expressionLatex: "0.7^3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.343, unit: "" }],
            correctLatex: "P = 0.7^3 = 0.343",
          },
          {
            id: "CC4",
            difficulty,
            stage,
            scenario: t.scenarios.dice_game,
            context: t.problems.three_dice_all_six,
            promptLatex: "P(\\text{all 6})",
            expressionLatex: "(\\frac{1}{6})^3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.0046, unit: "" }],
            correctLatex: "P = (\\frac{1}{6})^3 \\approx 0.0046",
          },
          {
            id: "CC5",
            difficulty,
            stage,
            scenario: t.scenarios.fc_basel,
            context: t.problems.fc_basel_at_least_one_win,
            promptLatex: "P(\\text{≥1 win})",
            expressionLatex: "1 - (0.4 \\times 0.7)",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.72, unit: "" }],
            correctLatex: "P = 1 - 0.28 = 0.72",
          },
        ],
        ADVANCED: [
          {
            id: "CA1",
            difficulty,
            stage,
            scenario: t.scenarios.novartis_qc,
            context: t.problems.quality_all_pass,
            promptLatex: "P(\\text{all 5 pass})",
            expressionLatex: "0.95^5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.774, unit: "" }],
            correctLatex: "P = 0.95^5 \\approx 0.774 = 77.4\\%",
          },
          {
            id: "CA2",
            difficulty,
            stage,
            scenario: t.scenarios.novartis_qc,
            context: t.problems.quality_at_least_4_pass,
            promptLatex: "P(\\text{≥4 pass})",
            expressionLatex: "0.95^5 + 5 \\times 0.95^4 \\times 0.05",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.977, unit: "" }],
            correctLatex: "P \\approx 0.977",
          },
          {
            id: "CA3",
            difficulty,
            stage,
            scenario: t.scenarios.four_buses,
            context: t.problems.four_buses_all_ontime,
            promptLatex: "P(\\text{all on time})",
            expressionLatex: "0.8^4",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.41, unit: "" }],
            correctLatex: "P = 0.8^4 \\approx 0.41",
          },
          {
            id: "CA4",
            difficulty,
            stage,
            scenario: t.scenarios.weather_basel,
            context: t.problems.week_no_rain,
            promptLatex: "P(\\text{no rain 7 days})",
            expressionLatex: "0.6^7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.028, unit: "" }],
            correctLatex: "P = 0.6^7 \\approx 0.028",
          },
          {
            id: "CA5",
            difficulty,
            stage,
            scenario: t.scenarios.exam_results,
            context: t.problems.five_students_all_pass,
            promptLatex: "P(\\text{all 5 pass})",
            expressionLatex: "0.85^5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.444, unit: "" }],
            correctLatex: "P = 0.85^5 \\approx 0.444",
          },
        ],
        ELITE: [
          {
            id: "CE1",
            difficulty,
            stage,
            scenario: t.scenarios.three_events,
            context: t.problems.three_coins_two_heads,
            promptLatex: "P(\\text{exactly 2 heads})",
            expressionLatex: "\\frac{3}{8}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.375, unit: "" }],
            correctLatex: "P = \\frac{3}{8} = 0.375 = 37.5\\%",
          },
          {
            id: "CE2",
            difficulty,
            stage,
            scenario: t.scenarios.three_events,
            context: t.problems.four_coins_exactly_3_heads,
            promptLatex: "P(\\text{exactly 3})",
            expressionLatex: "\\frac{4}{16}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\frac{4}{16} = 0.25",
          },
          {
            id: "CE3",
            difficulty,
            stage,
            scenario: t.scenarios.novartis_qc,
            context: t.problems.quality_exactly_4_pass,
            promptLatex: "P(\\text{exactly 4})",
            expressionLatex: "5 \\times 0.95^4 \\times 0.05",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.204, unit: "" }],
            correctLatex: "P \\approx 0.204",
          },
          {
            id: "CE4",
            difficulty,
            stage,
            scenario: t.scenarios.three_events,
            context: t.problems.five_coins_at_least_4_heads,
            promptLatex: "P(\\text{≥4 heads})",
            expressionLatex: "\\frac{6}{32}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.188, unit: "" }],
            correctLatex: "P = \\frac{6}{32} \\approx 0.188",
          },
          {
            id: "CE5",
            difficulty,
            stage,
            scenario: t.scenarios.complex_event,
            context: t.problems.birthday_paradox_simple,
            promptLatex: "P(\\text{match})",
            expressionLatex: "1 - \\frac{365 \\times 364}{365^2}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.0027, unit: "" }],
            correctLatex: "P \\approx 0.0027",
          },
        ],
      },
      DATA_STATS: {
        BASIC: [
          {
            id: "D1",
            difficulty,
            stage,
            scenario: t.scenarios.temperature,
            context: t.problems.avg_temperature,
            promptLatex: "\\text{Average}",
            expressionLatex: "\\frac{18+22+20+19+21+23+20}{7}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx.x", expected: 20.4, unit: "°C" }],
            correctLatex: "\\bar{x} \\approx 20.4°C",
          },
          {
            id: "D2",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.simple_average_5,
            promptLatex: "\\text{Average}",
            expressionLatex: "\\frac{80+85+90+75+95}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 85, unit: "" }],
            correctLatex: "\\bar{x} = 85",
          },
          {
            id: "D3",
            difficulty,
            stage,
            scenario: t.scenarios.pocket_money,
            context: t.problems.simple_sum,
            promptLatex: "\\text{Total}",
            expressionLatex: "40+25+20+15",
            targetLatex: "T",
            slots: [{ id: "T", labelLatex: "T", placeholder: "xxx", expected: 100, unit: "CHF" }],
            correctLatex: "T = 100 \\text{ CHF}",
          },
          {
            id: "D4",
            difficulty,
            stage,
            scenario: t.scenarios.temperature,
            context: t.problems.avg_temperature_5_days,
            promptLatex: "\\text{Average}",
            expressionLatex: "\\frac{15+18+20+17+20}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 18, unit: "°C" }],
            correctLatex: "\\bar{x} = 18°C",
          },
          {
            id: "D5",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.median_5_values,
            promptLatex: "\\text{Median}",
            expressionLatex: "\\text{middle of } 10,12,15,18,20",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx", expected: 15, unit: "" }],
            correctLatex: "M = 15",
          },
        ],
        CORE: [
          {
            id: "D6",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.class_average,
            promptLatex: "\\text{Class Average}",
            expressionLatex: "\\frac{\\sum scores}{n}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 78, unit: "" }],
            correctLatex: "\\bar{x} = 78",
          },
          {
            id: "D7",
            difficulty,
            stage,
            scenario: t.scenarios.pocket_money,
            context: t.problems.spending_analysis,
            promptLatex: "\\text{Food %}",
            expressionLatex: "\\frac{40}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "\\%", placeholder: "xx", expected: 40, unit: "%" }],
            correctLatex: "40\\%",
          },
          {
            id: "D8",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.median_even_count,
            promptLatex: "\\text{Median}",
            expressionLatex: "\\frac{75+80}{2}",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx.x", expected: 77.5, unit: "" }],
            correctLatex: "M = 77.5",
          },
          {
            id: "D9",
            difficulty,
            stage,
            scenario: t.scenarios.temperature,
            context: t.problems.range_calculation,
            promptLatex: "\\text{Range}",
            expressionLatex: "23 - 15",
            targetLatex: "R",
            slots: [{ id: "R", labelLatex: "R", placeholder: "x", expected: 8, unit: "°C" }],
            correctLatex: "R = 8°C",
          },
          {
            id: "D10",
            difficulty,
            stage,
            scenario: t.scenarios.pocket_money,
            context: t.problems.percentage_transport,
            promptLatex: "\\text{Transport %}",
            expressionLatex: "\\frac{25}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "\\%", placeholder: "xx", expected: 25, unit: "%" }],
            correctLatex: "25\\%",
          },
        ],
        ADVANCED: [
          {
            id: "D11",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.weighted_average,
            promptLatex: "\\text{Weighted Avg}",
            expressionLatex: "\\frac{80 \\times 2 + 90 \\times 3}{5}",
            targetLatex: "\\bar{x}_w",
            slots: [{ id: "avg", labelLatex: "\\bar{x}_w", placeholder: "xx", expected: 86, unit: "" }],
            correctLatex: "\\bar{x}_w = 86",
          },
          {
            id: "D12",
            difficulty,
            stage,
            scenario: t.scenarios.data_comparison,
            context: t.problems.median_vs_mean,
            promptLatex: "\\text{Median}",
            expressionLatex: "\\text{middle value}",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx", expected: 15, unit: "" }],
            correctLatex: "M = 15",
          },
          {
            id: "D13",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.mode_calculation,
            promptLatex: "\\text{Mode}",
            expressionLatex: "\\text{most frequent}",
            targetLatex: "Mo",
            slots: [{ id: "Mo", labelLatex: "Mo", placeholder: "xx", expected: 85, unit: "" }],
            correctLatex: "Mo = 85",
          },
          {
            id: "D14",
            difficulty,
            stage,
            scenario: t.scenarios.pocket_money,
            context: t.problems.budget_remaining,
            promptLatex: "\\text{Remaining}",
            expressionLatex: "100 - 40 - 25 - 20",
            targetLatex: "R",
            slots: [{ id: "R", labelLatex: "R", placeholder: "xx", expected: 15, unit: "CHF" }],
            correctLatex: "R = 15 \\text{ CHF}",
          },
          {
            id: "D15",
            difficulty,
            stage,
            scenario: t.scenarios.temperature,
            context: t.problems.quartile_calculation,
            promptLatex: "\\text{Q1}",
            expressionLatex: "\\text{25th percentile}",
            targetLatex: "Q_1",
            slots: [{ id: "Q1", labelLatex: "Q_1", placeholder: "xx", expected: 17, unit: "°C" }],
            correctLatex: "Q_1 = 17°C",
          },
        ],
        ELITE: [
          {
            id: "D16",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.standard_deviation_simple,
            promptLatex: "\\text{Variance}",
            expressionLatex: "\\frac{\\sum(x_i - \\bar{x})^2}{n}",
            targetLatex: "\\sigma^2",
            slots: [{ id: "var", labelLatex: "\\sigma^2", placeholder: "xx", expected: 50, unit: "" }],
            correctLatex: "\\sigma^2 = 50",
          },
          {
            id: "D17",
            difficulty,
            stage,
            scenario: t.scenarios.data_comparison,
            context: t.problems.outlier_effect,
            promptLatex: "\\text{New Mean}",
            expressionLatex: "\\frac{10+12+15+18+100}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 31, unit: "" }],
            correctLatex: "\\bar{x} = 31",
          },
          {
            id: "D18",
            difficulty,
            stage,
            scenario: t.scenarios.test_scores,
            context: t.problems.interquartile_range,
            promptLatex: "\\text{IQR}",
            expressionLatex: "Q_3 - Q_1",
            targetLatex: "IQR",
            slots: [{ id: "IQR", labelLatex: "IQR", placeholder: "xx", expected: 10, unit: "" }],
            correctLatex: "IQR = 10",
          },
          {
            id: "D19",
            difficulty,
            stage,
            scenario: t.scenarios.pocket_money,
            context: t.problems.percentage_change,
            promptLatex: "\\text{% Change}",
            expressionLatex: "\\frac{120-100}{100} \\times 100",
            targetLatex: "\\Delta\\%",
            slots: [{ id: "pct", labelLatex: "\\Delta\\%", placeholder: "xx", expected: 20, unit: "%" }],
            correctLatex: "\\Delta\\% = 20\\%",
          },
          {
            id: "D20",
            difficulty,
            stage,
            scenario: t.scenarios.data_comparison,
            context: t.problems.correlation_direction,
            promptLatex: "\\text{Correlation}",
            expressionLatex: "\\text{positive/negative}",
            targetLatex: "r",
            slots: [{ id: "r", labelLatex: "r", placeholder: "1 or -1", expected: 1, unit: "" }],
            correctLatex: "r > 0 \\text{ (positive)}",
          },
        ],
      },
    };

    return pools[stage][difficulty] || [];
  }, []);

  const buildPool = useCallback((difficulty: Difficulty, stage: Stage) => buildStagePool(t, difficulty, stage), [t, buildStagePool]);

  const {
    currentQuest: quest,
    stage,
    inputs,
    setInputs,
    lastCheck,
    verify,
    next,
    handleStageChange,
    difficulty,
    handleDifficultyChange,
  } = useQuestManager<ProbQuest, Stage>({
    buildPool,
    initialStage: "BASIC_PROB",
    tolerance: 0.01,
  });

  useEffect(() => {
    if (lastCheck?.ok) {
      completeStage("sm2-08", stage);
    }
  }, [lastCheck, completeStage, stage]);

  return (
    <ChamberLayout
      title={t.title}
      moduleCode="SM2.08"
      difficulty={difficulty}
      onDifficultyChange={handleDifficultyChange}
      stages={[
        { id: "BASIC_PROB", label: t.stages.basic_prob },
        { id: "LOTTERY", label: t.stages.lottery },
        { id: "COMBINED", label: t.stages.combined },
        { id: "DATA_STATS", label: t.stages.data_stats },
      ]}
      currentStage={stage}
      onStageChange={(s) => handleStageChange(s as Stage)}
      onVerify={verify}
      onNext={next}
      checkStatus={lastCheck}
      footerLeft={t.footer_left}
      translations={{
        back: t.back,
        check: t.check,
        next: t.next,
        correct: t.correct,
        incorrect: t.incorrect,
        ready: t.ready,
        monitor_title: t.monitor_title,
        difficulty: {
          basic: t.difficulty.basic,
          core: t.difficulty.core,
          advanced: t.difficulty.advanced,
          elite: t.difficulty.elite,
        },
      }}
      monitorContent={
        <div className="space-y-4">
          <ProbabilityVisualizer stage={stage} language={currentLanguage as "EN" | "CN" | "DE"} />
          <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black">
            {t.formula_title}
          </div>
          <div className="rounded-xl border border-cyan-500/30 bg-black/50 p-4">
            <BlockMath math="P(E) = \frac{\text{favorable outcomes}}{\text{total outcomes}}" />
          </div>
        </div>
      }
    >
      <div className="space-y-8">
        {quest?.scenario && (
          <div className="p-6 bg-purple-500/10 border border-purple-500/30 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-purple-400 font-black mb-3">
              {t.basel_scenario}
            </div>
            <p className="text-white/90 leading-relaxed font-medium">{quest.scenario}</p>
          </div>
        )}

        {quest?.context && (
          <div className="p-6 bg-cyan-500/5 border border-cyan-500/20 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black mb-3">
              {t.scenario_title}
            </div>
            <p className="text-white/80 leading-relaxed">{quest.context}</p>
          </div>
        )}

        <div className="text-center space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white/60 font-black">
            {t.calculate_title}
          </div>
          <div className="text-3xl text-white font-black">
            <InlineMath math={quest?.promptLatex || ""} />
          </div>
        </div>

        {quest?.expressionLatex && (
          <div className="text-center p-4 bg-white/5 border border-white/10 rounded-xl">
            <BlockMath math={quest.expressionLatex} />
          </div>
        )}

        <div className="max-w-md mx-auto space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white font-black text-center">
            {t.answer_title}
          </div>
          {quest?.slots.map((slot) => (
            <div key={slot.id} className="space-y-2">
              <label className="text-sm text-white/70 font-mono">
                <InlineMath math={slot.labelLatex} />
              </label>
              <input
                value={inputs[slot.id] ?? ""}
                onChange={(e) => setInputs((prev) => ({ ...prev, [slot.id]: e.target.value }))}
                className="w-full bg-black border-2 border-cyan-500/50 p-4 text-center outline-none focus:border-cyan-400 placeholder:text-white/40 font-black text-2xl text-white rounded-lg"
                placeholder={slot.placeholder}
              />
            </div>
          ))}
        </div>

        {lastCheck?.ok && quest?.correctLatex && (
          <div className="text-center p-4 bg-green-500/10 border border-green-500/30 rounded-xl">
            <div className="text-green-400 font-black mb-2">{t.solution_title}</div>
            <BlockMath math={quest.correctLatex} />
          </div>
        )}
      </div>
    </ChamberLayout>
  );
}
