"use client";

import { useEffect, useCallback } from "react";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";
import { useAppStore } from "@/lib/store";
import { useLanguage } from "@/lib/i18n";
import ChamberLayout from "@/components/layout/ChamberLayout";
import ProbabilityVisualizer from "@/components/chamber/sm2-08/ProbabilityVisualizer";
import { Difficulty, Quest, useQuestManager } from "@/hooks/useQuestManager";

type Stage = "BASIC_PROB" | "LOTTERY" | "COMBINED" | "DATA_STATS";
type ProbQuest = Quest & { stage: Stage; context?: string; scenario?: string };

export default function SM208Page() {
  const { completeStage } = useAppStore();
  const { t, currentLanguage } = useLanguage();

  const sm2_08_t = {
    scenarios: {
      bus_punctuality: t("sm2_08.scenarios.bus_punctuality"),
      card_game: t("sm2_08.scenarios.card_game"),
      coin_flip: t("sm2_08.scenarios.coin_flip"),
      complex_event: t("sm2_08.scenarios.complex_event"),
      data_comparison: t("sm2_08.scenarios.data_comparison"),
      dice_advanced: t("sm2_08.scenarios.dice_advanced"),
      dice_game: t("sm2_08.scenarios.dice_game"),
      dice_two: t("sm2_08.scenarios.dice_two"),
      dice_win_condition: t("sm2_08.scenarios.dice_win_condition"),
      exam_results: t("sm2_08.scenarios.exam_results"),
      fasnacht_game: t("sm2_08.scenarios.fasnacht_game"),
      fc_basel: t("sm2_08.scenarios.fc_basel"),
      four_buses: t("sm2_08.scenarios.four_buses"),
      novartis_qc: t("sm2_08.scenarios.novartis_qc"),
      pocket_money: t("sm2_08.scenarios.pocket_money"),
      school_cafeteria: t("sm2_08.scenarios.school_cafeteria"),
      school_raffle: t("sm2_08.scenarios.school_raffle"),
      swiss_lotto_simple: t("sm2_08.scenarios.swiss_lotto_simple"),
      temperature: t("sm2_08.scenarios.temperature"),
      test_scores: t("sm2_08.scenarios.test_scores"),
      three_buses: t("sm2_08.scenarios.three_buses"),
      three_events: t("sm2_08.scenarios.three_events"),
      tram_punctuality: t("sm2_08.scenarios.tram_punctuality"),
      two_buses: t("sm2_08.scenarios.two_buses"),
      two_coins: t("sm2_08.scenarios.two_coins"),
      two_dice: t("sm2_08.scenarios.two_dice"),
      weather_basel: t("sm2_08.scenarios.weather_basel"),
    },
    problems: {
      avg_temperature: t("sm2_08.problems.avg_temperature"),
      avg_temperature_5_days: t("sm2_08.problems.avg_temperature_5_days"),
      birthday_paradox_simple: t("sm2_08.problems.birthday_paradox_simple"),
      budget_remaining: t("sm2_08.problems.budget_remaining"),
      bus_ontime_16_20: t("sm2_08.problems.bus_ontime_16_20"),
      bus_ontime_18_20: t("sm2_08.problems.bus_ontime_18_20"),
      cafeteria_pizza: t("sm2_08.problems.cafeteria_pizza"),
      card_ace_or_king: t("sm2_08.problems.card_ace_or_king"),
      card_face: t("sm2_08.problems.card_face"),
      card_heart: t("sm2_08.problems.card_heart"),
      card_poker_pair: t("sm2_08.problems.card_poker_pair"),
      card_red: t("sm2_08.problems.card_red"),
      card_spade_face: t("sm2_08.problems.card_spade_face"),
      card_three_hearts: t("sm2_08.problems.card_three_hearts"),
      card_two_red: t("sm2_08.problems.card_two_red"),
      class_average: t("sm2_08.problems.class_average"),
      coin_five_exactly_2_heads: t("sm2_08.problems.coin_five_exactly_2_heads"),
      coin_four_at_least_3_heads: t("sm2_08.problems.coin_four_at_least_3_heads"),
      coin_heads: t("sm2_08.problems.coin_heads"),
      coin_three_all_heads: t("sm2_08.problems.coin_three_all_heads"),
      coin_two_heads: t("sm2_08.problems.coin_two_heads"),
      correlation_direction: t("sm2_08.problems.correlation_direction"),
      dice_even: t("sm2_08.problems.dice_even"),
      dice_greater_4: t("sm2_08.problems.dice_greater_4"),
      dice_not_six: t("sm2_08.problems.dice_not_six"),
      dice_prime: t("sm2_08.problems.dice_prime"),
      dice_roll_3: t("sm2_08.problems.dice_roll_3"),
      dice_sum_2_3_12: t("sm2_08.problems.dice_sum_2_3_12"),
      dice_sum_6: t("sm2_08.problems.dice_sum_6"),
      dice_sum_7: t("sm2_08.problems.dice_sum_7"),
      dice_sum_7_or_11: t("sm2_08.problems.dice_sum_7_or_11"),
      dice_sum_9: t("sm2_08.problems.dice_sum_9"),
      dice_sum_less_5: t("sm2_08.problems.dice_sum_less_5"),
      exam_pass: t("sm2_08.problems.exam_pass"),
      fc_basel_at_least_one_win: t("sm2_08.problems.fc_basel_at_least_one_win"),
      fc_basel_wins: t("sm2_08.problems.fc_basel_wins"),
      five_coins_at_least_4_heads: t("sm2_08.problems.five_coins_at_least_4_heads"),
      five_students_all_pass: t("sm2_08.problems.five_students_all_pass"),
      four_buses_all_ontime: t("sm2_08.problems.four_buses_all_ontime"),
      four_coins_exactly_3_heads: t("sm2_08.problems.four_coins_exactly_3_heads"),
      interquartile_range: t("sm2_08.problems.interquartile_range"),
      lotto_4_from_8: t("sm2_08.problems.lotto_4_from_8"),
      lotto_5_from_10: t("sm2_08.problems.lotto_5_from_10"),
      lotto_simple: t("sm2_08.problems.lotto_simple"),
      median_5_values: t("sm2_08.problems.median_5_values"),
      median_even_count: t("sm2_08.problems.median_even_count"),
      median_vs_mean: t("sm2_08.problems.median_vs_mean"),
      mode_calculation: t("sm2_08.problems.mode_calculation"),
      outlier_effect: t("sm2_08.problems.outlier_effect"),
      percentage_change: t("sm2_08.problems.percentage_change"),
      percentage_transport: t("sm2_08.problems.percentage_transport"),
      quality_all_pass: t("sm2_08.problems.quality_all_pass"),
      quality_at_least_4_pass: t("sm2_08.problems.quality_at_least_4_pass"),
      quality_exactly_4_pass: t("sm2_08.problems.quality_exactly_4_pass"),
      quartile_calculation: t("sm2_08.problems.quartile_calculation"),
      range_calculation: t("sm2_08.problems.range_calculation"),
      school_raffle_2_tickets: t("sm2_08.problems.school_raffle_2_tickets"),
      school_raffle_5_tickets: t("sm2_08.problems.school_raffle_5_tickets"),
      school_raffle_win: t("sm2_08.problems.school_raffle_win"),
      simple_average_5: t("sm2_08.problems.simple_average_5"),
      simple_sum: t("sm2_08.problems.simple_sum"),
      spending_analysis: t("sm2_08.problems.spending_analysis"),
      standard_deviation_simple: t("sm2_08.problems.standard_deviation_simple"),
      three_buses_all_ontime: t("sm2_08.problems.three_buses_all_ontime"),
      three_coins_two_heads: t("sm2_08.problems.three_coins_two_heads"),
      three_days_all_sunny: t("sm2_08.problems.three_days_all_sunny"),
      three_dice_all_six: t("sm2_08.problems.three_dice_all_six"),
      tram_ontime_17_20: t("sm2_08.problems.tram_ontime_17_20"),
      two_buses_ontime: t("sm2_08.problems.two_buses_ontime"),
      two_coins_both_heads: t("sm2_08.problems.two_coins_both_heads"),
      two_days_both_sunny: t("sm2_08.problems.two_days_both_sunny"),
      two_dice_both_even: t("sm2_08.problems.two_dice_both_even"),
      two_dice_doubles: t("sm2_08.problems.two_dice_doubles"),
      two_dice_sum_10: t("sm2_08.problems.two_dice_sum_10"),
      two_dice_sum_8: t("sm2_08.problems.two_dice_sum_8"),
      two_students_both_pass: t("sm2_08.problems.two_students_both_pass"),
      weather_rain_12_30: t("sm2_08.problems.weather_rain_12_30"),
      weather_sunny_21_30: t("sm2_08.problems.weather_sunny_21_30"),
      week_no_rain: t("sm2_08.problems.week_no_rain"),
      weighted_average: t("sm2_08.problems.weighted_average"),
    },
  };

  const buildStagePool = useCallback((tObj: typeof sm2_08_t, difficulty: Difficulty, stage: Stage): ProbQuest[] => {
    const pools: Record<Stage, Record<Difficulty, ProbQuest[]>> = {
      BASIC_PROB: {
        BASIC: [
          {
            id: "B1",
            difficulty,
            stage,
            scenario: tObj.scenarios.bus_punctuality,
            context: tObj.problems.bus_ontime_16_20,
            promptLatex: "P(\\\\text{on time})",
            expressionLatex: "\\\\frac{16}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.8, unit: "" }],
            correctLatex: "P = \\\\frac{16}{20} = 0.8 = 80\\%",
          },
          {
            id: "B2",
            difficulty,
            stage,
            scenario: tObj.scenarios.weather_basel,
            context: tObj.problems.weather_rain_12_30,
            promptLatex: "P(\\\\text{rain})",
            expressionLatex: "\\\\frac{12}{30}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.4, unit: "" }],
            correctLatex: "P = \\\\frac{12}{30} = 0.4 = 40\\%",
          },
          {
            id: "B3",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_game,
            context: tObj.problems.dice_roll_3,
            promptLatex: "P(3)",
            expressionLatex: "\\\\frac{1}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\\\frac{1}{6} \\approx 0.167",
          },
          {
            id: "B4",
            difficulty,
            stage,
            scenario: tObj.scenarios.coin_flip,
            context: tObj.problems.coin_heads,
            promptLatex: "P(\\\\text{heads})",
            expressionLatex: "\\\\frac{1}{2}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\\\frac{1}{2} = 0.5 = 50\\%",
          },
          {
            id: "B5",
            difficulty,
            stage,
            scenario: tObj.scenarios.bus_punctuality,
            context: tObj.problems.bus_ontime_18_20,
            promptLatex: "P(\\\\text{on time})",
            expressionLatex: "\\\\frac{18}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.9, unit: "" }],
            correctLatex: "P = \\\\frac{18}{20} = 0.9 = 90\\%",
          },
        ],
        CORE: [
          {
            id: "C1",
            difficulty,
            stage,
            scenario: tObj.scenarios.school_cafeteria,
            context: tObj.problems.cafeteria_pizza,
            promptLatex: "P(\\\\text{pizza})",
            expressionLatex: "\\\\frac{3}{5}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.6, unit: "" }],
            correctLatex: "P = \\\\frac{3}{5} = 0.6 = 60\\%",
          },
          {
            id: "C2",
            difficulty,
            stage,
            scenario: tObj.scenarios.exam_results,
            context: tObj.problems.exam_pass,
            promptLatex: "P(\\\\text{pass})",
            expressionLatex: "\\\\frac{85}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.85, unit: "" }],
            correctLatex: "P = 0.85 = 85\\%",
          },
          {
            id: "C3",
            difficulty,
            stage,
            scenario: tObj.scenarios.weather_basel,
            context: tObj.problems.weather_sunny_21_30,
            promptLatex: "P(\\\\text{sunny})",
            expressionLatex: "\\\\frac{21}{30}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.7, unit: "" }],
            correctLatex: "P = \\\\frac{21}{30} = 0.7 = 70\\%",
          },
          {
            id: "C4",
            difficulty,
            stage,
            scenario: tObj.scenarios.tram_punctuality,
            context: tObj.problems.tram_ontime_17_20,
            promptLatex: "P(\\\\text{on time})",
            expressionLatex: "\\\\frac{17}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.85, unit: "" }],
            correctLatex: "P = \\\\frac{17}{20} = 0.85 = 85\\%",
          },
          {
            id: "C5",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_game,
            context: tObj.problems.dice_greater_4,
            promptLatex: "P(>4)",
            expressionLatex: "\\\\frac{2}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.333, unit: "" }],
            correctLatex: "P = \\\\frac{2}{6} \\approx 0.333",
          },
        ],
        ADVANCED: [
          {
            id: "A1",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_game,
            context: tObj.problems.dice_even,
            promptLatex: "P(\\\\text{even})",
            expressionLatex: "\\\\frac{3}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\\\frac{3}{6} = 0.5 = 50\\%",
          },
          {
            id: "A2",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_heart,
            promptLatex: "P(\\\\text{heart})",
            expressionLatex: "\\\\frac{13}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\\\frac{13}{52} = 0.25 = 25\\%",
          },
          {
            id: "A3",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_red,
            promptLatex: "P(\\\\text{red})",
            expressionLatex: "\\\\frac{26}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\\\frac{26}{52} = 0.5 = 50\\%",
          },
          {
            id: "A4",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_two,
            context: tObj.problems.two_dice_sum_8,
            promptLatex: "P(\\\\text{sum}=8)",
            expressionLatex: "\\\\frac{5}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.139, unit: "" }],
            correctLatex: "P = \\\\frac{5}{36} \\approx 0.139",
          },
          {
            id: "A5",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_face,
            promptLatex: "P(\\\\text{face})",
            expressionLatex: "\\\\frac{12}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.231, unit: "" }],
            correctLatex: "P = \\\\frac{12}{52} \\approx 0.231",
          },
        ],
        ELITE: [
          {
            id: "E1",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_advanced,
            context: tObj.problems.dice_prime,
            promptLatex: "P(\\\\text{prime})",
            expressionLatex: "\\\\frac{3}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.x", expected: 0.5, unit: "" }],
            correctLatex: "P = \\\\frac{3}{6} = 0.5 = 50\\%",
          },
          {
            id: "E2",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_two,
            context: tObj.problems.two_dice_sum_10,
            promptLatex: "P(\\\\text{sum}=10)",
            expressionLatex: "\\\\frac{3}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.083, unit: "" }],
            correctLatex: "P = \\\\frac{3}{36} \\approx 0.083",
          },
          {
            id: "E3",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_ace_or_king,
            promptLatex: "P(\\\\text{A or K})",
            expressionLatex: "\\\\frac{8}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.154, unit: "" }],
            correctLatex: "P = \\\\frac{8}{52} \\approx 0.154",
          },
          {
            id: "E4",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_two,
            context: tObj.problems.two_dice_doubles,
            promptLatex: "P(\\\\text{doubles})",
            expressionLatex: "\\\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\\\frac{6}{36} \\approx 0.167",
          },
          {
            id: "E5",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_spade_face,
            promptLatex: "P(\\\\text{spade face})",
            expressionLatex: "\\\\frac{3}{52}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.058, unit: "" }],
            correctLatex: "P = \\\\frac{3}{52} \\approx 0.058",
          },
        ],
      },
      LOTTERY: {
        BASIC: [
          {
            id: "L1",
            difficulty,
            stage,
            scenario: tObj.scenarios.school_raffle,
            context: tObj.problems.school_raffle_win,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{3}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.03, unit: "" }],
            correctLatex: "P = \\\\frac{3}{100} = 0.03 = 3\\%",
          },
          {
            id: "L2",
            difficulty,
            stage,
            scenario: tObj.scenarios.school_raffle,
            context: tObj.problems.school_raffle_5_tickets,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{5}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.05, unit: "" }],
            correctLatex: "P = \\\\frac{5}{100} = 0.05 = 5\\%",
          },
          {
            id: "L3",
            difficulty,
            stage,
            scenario: tObj.scenarios.coin_flip,
            context: tObj.problems.coin_two_heads,
            promptLatex: "P(\\\\text{2 heads})",
            expressionLatex: "\\\\frac{1}{4}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\\\frac{1}{4} = 0.25 = 25\\%",
          },
          {
            id: "L4",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_game,
            context: tObj.problems.dice_not_six,
            promptLatex: "P(\\\\text{not 6})",
            expressionLatex: "\\\\frac{5}{6}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.833, unit: "" }],
            correctLatex: "P = \\\\frac{5}{6} \\approx 0.833",
          },
          {
            id: "L5",
            difficulty,
            stage,
            scenario: tObj.scenarios.school_raffle,
            context: tObj.problems.school_raffle_2_tickets,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{2}{50}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.04, unit: "" }],
            correctLatex: "P = \\\\frac{2}{50} = 0.04 = 4\\%",
          },
        ],
        CORE: [
          {
            id: "L6",
            difficulty,
            stage,
            scenario: tObj.scenarios.fasnacht_game,
            context: tObj.problems.dice_sum_7,
            promptLatex: "P(\\\\text{sum}=7)",
            expressionLatex: "\\\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\\\frac{6}{36} \\approx 0.167 = 16.7\\%",
          },
          {
            id: "L7",
            difficulty,
            stage,
            scenario: tObj.scenarios.fasnacht_game,
            context: tObj.problems.dice_sum_9,
            promptLatex: "P(\\\\text{sum}=9)",
            expressionLatex: "\\\\frac{4}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.111, unit: "" }],
            correctLatex: "P = \\\\frac{4}{36} \\approx 0.111",
          },
          {
            id: "L8",
            difficulty,
            stage,
            scenario: tObj.scenarios.coin_flip,
            context: tObj.problems.coin_three_all_heads,
            promptLatex: "P(\\\\text{3 heads})",
            expressionLatex: "\\\\frac{1}{8}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.125, unit: "" }],
            correctLatex: "P = \\\\frac{1}{8} = 0.125",
          },
          {
            id: "L9",
            difficulty,
            stage,
            scenario: tObj.scenarios.fasnacht_game,
            context: tObj.problems.dice_sum_6,
            promptLatex: "P(\\\\text{sum}=6)",
            expressionLatex: "\\\\frac{5}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.139, unit: "" }],
            correctLatex: "P = \\\\frac{5}{36} \\approx 0.139",
          },
          {
            id: "L10",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_two_red,
            promptLatex: "P(\\\\text{2 red})",
            expressionLatex: "\\\\frac{26}{52} \\times \\\\frac{25}{51}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.245, unit: "" }],
            correctLatex: "P \\approx 0.245",
          },
        ],
        ADVANCED: [
          {
            id: "L11",
            difficulty,
            stage,
            scenario: tObj.scenarios.swiss_lotto_simple,
            context: tObj.problems.lotto_simple,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{1}{20}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.05, unit: "" }],
            correctLatex: "P = \\\\frac{1}{20} = 0.05 = 5\\%",
          },
          {
            id: "L12",
            difficulty,
            stage,
            scenario: tObj.scenarios.swiss_lotto_simple,
            context: tObj.problems.lotto_4_from_8,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{1}{70}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.014, unit: "" }],
            correctLatex: "P = \\\\frac{1}{70} \\approx 0.014",
          },
          {
            id: "L13",
            difficulty,
            stage,
            scenario: tObj.scenarios.fasnacht_game,
            context: tObj.problems.dice_sum_less_5,
            promptLatex: "P(\\\\text{sum}<5)",
            expressionLatex: "\\\\frac{6}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.167, unit: "" }],
            correctLatex: "P = \\\\frac{6}{36} \\approx 0.167",
          },
          {
            id: "L14",
            difficulty,
            stage,
            scenario: tObj.scenarios.coin_flip,
            context: tObj.problems.coin_four_at_least_3_heads,
            promptLatex: "P(\\geq 3 \\\\text{ heads})",
            expressionLatex: "\\\\frac{5}{16}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.313, unit: "" }],
            correctLatex: "P = \\\\frac{5}{16} \\approx 0.313",
          },
          {
            id: "L15",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_three_hearts,
            promptLatex: "P(\\\\text{3 hearts})",
            expressionLatex: "\\\\frac{13}{52} \\times \\\\frac{12}{51} \\times \\\\frac{11}{50}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.013, unit: "" }],
            correctLatex: "P \\approx 0.013",
          },
        ],
        ELITE: [
          {
            id: "L16",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_win_condition,
            context: tObj.problems.dice_sum_7_or_11,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{8}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.222, unit: "" }],
            correctLatex: "P = \\\\frac{8}{36} \\approx 0.222 = 22.2\\%",
          },
          {
            id: "L17",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_win_condition,
            context: tObj.problems.dice_sum_2_3_12,
            promptLatex: "P(\\\\text{lose})",
            expressionLatex: "\\\\frac{4}{36}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.111, unit: "" }],
            correctLatex: "P = \\\\frac{4}{36} \\approx 0.111",
          },
          {
            id: "L18",
            difficulty,
            stage,
            scenario: tObj.scenarios.swiss_lotto_simple,
            context: tObj.problems.lotto_5_from_10,
            promptLatex: "P(\\\\text{win})",
            expressionLatex: "\\\\frac{1}{252}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.004, unit: "" }],
            correctLatex: "P = \\\\frac{1}{252} \\approx 0.004",
          },
          {
            id: "L19",
            difficulty,
            stage,
            scenario: tObj.scenarios.coin_flip,
            context: tObj.problems.coin_five_exactly_2_heads,
            promptLatex: "P(\\\\text{exactly 2})",
            expressionLatex: "\\\\frac{10}{32}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.313, unit: "" }],
            correctLatex: "P = \\\\frac{10}{32} \\approx 0.313",
          },
          {
            id: "L20",
            difficulty,
            stage,
            scenario: tObj.scenarios.card_game,
            context: tObj.problems.card_poker_pair,
            promptLatex: "P(\\\\text{pair})",
            expressionLatex: "\\\\text{complex}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.423, unit: "" }],
            correctLatex: "P \\approx 0.423",
          },
        ],
      },
      COMBINED: {
        BASIC: [
          {
            id: "CB1",
            difficulty,
            stage,
            scenario: tObj.scenarios.two_buses,
            context: tObj.problems.two_buses_ontime,
            promptLatex: "P(\\\\text{both on time})",
            expressionLatex: "0.8 \\times 0.7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.56, unit: "" }],
            correctLatex: "P = 0.8 \\times 0.7 = 0.56 = 56\\%",
          },
          {
            id: "CB2",
            difficulty,
            stage,
            scenario: tObj.scenarios.two_coins,
            context: tObj.problems.two_coins_both_heads,
            promptLatex: "P(\\\\text{both heads})",
            expressionLatex: "0.5 \\times 0.5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = 0.5 \\times 0.5 = 0.25",
          },
          {
            id: "CB3",
            difficulty,
            stage,
            scenario: tObj.scenarios.two_dice,
            context: tObj.problems.two_dice_both_even,
            promptLatex: "P(\\\\text{both even})",
            expressionLatex: "0.5 \\times 0.5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = 0.5 \\times 0.5 = 0.25",
          },
          {
            id: "CB4",
            difficulty,
            stage,
            scenario: tObj.scenarios.weather_basel,
            context: tObj.problems.two_days_both_sunny,
            promptLatex: "P(\\\\text{both sunny})",
            expressionLatex: "0.7 \\times 0.7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.49, unit: "" }],
            correctLatex: "P = 0.7 \\times 0.7 = 0.49",
          },
          {
            id: "CB5",
            difficulty,
            stage,
            scenario: tObj.scenarios.exam_results,
            context: tObj.problems.two_students_both_pass,
            promptLatex: "P(\\\\text{both pass})",
            expressionLatex: "0.85 \\times 0.85",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.723, unit: "" }],
            correctLatex: "P = 0.85 \\times 0.85 \\approx 0.723",
          },
        ],
        CORE: [
          {
            id: "CC1",
            difficulty,
            stage,
            scenario: tObj.scenarios.fc_basel,
            context: tObj.problems.fc_basel_wins,
            promptLatex: "P(\\\\text{both win})",
            expressionLatex: "0.6 \\times 0.3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.18, unit: "" }],
            correctLatex: "P = 0.6 \\times 0.3 = 0.18 = 18\\%",
          },
          {
            id: "CC2",
            difficulty,
            stage,
            scenario: tObj.scenarios.three_buses,
            context: tObj.problems.three_buses_all_ontime,
            promptLatex: "P(\\\\text{all on time})",
            expressionLatex: "0.8 \\times 0.75 \\times 0.9",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.54, unit: "" }],
            correctLatex: "P = 0.8 \\times 0.75 \\times 0.9 = 0.54",
          },
          {
            id: "CC3",
            difficulty,
            stage,
            scenario: tObj.scenarios.weather_basel,
            context: tObj.problems.three_days_all_sunny,
            promptLatex: "P(\\\\text{all sunny})",
            expressionLatex: "0.7^3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.343, unit: "" }],
            correctLatex: "P = 0.7^3 = 0.343",
          },
          {
            id: "CC4",
            difficulty,
            stage,
            scenario: tObj.scenarios.dice_game,
            context: tObj.problems.three_dice_all_six,
            promptLatex: "P(\\\\text{all 6})",
            expressionLatex: "(\\\\frac{1}{6})^3",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.0046, unit: "" }],
            correctLatex: "P = (\\\\frac{1}{6})^3 \\approx 0.0046",
          },
          {
            id: "CC5",
            difficulty,
            stage,
            scenario: tObj.scenarios.fc_basel,
            context: tObj.problems.fc_basel_at_least_one_win,
            promptLatex: "P(\\\\text{≥1 win})",
            expressionLatex: "1 - (0.4 \\times 0.7)",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.72, unit: "" }],
            correctLatex: "P = 1 - 0.28 = 0.72",
          },
        ],
        ADVANCED: [
          {
            id: "CA1",
            difficulty,
            stage,
            scenario: tObj.scenarios.novartis_qc,
            context: tObj.problems.quality_all_pass,
            promptLatex: "P(\\\\text{all 5 pass})",
            expressionLatex: "0.95^5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.774, unit: "" }],
            correctLatex: "P = 0.95^5 \\approx 0.774 = 77.4\\%",
          },
          {
            id: "CA2",
            difficulty,
            stage,
            scenario: tObj.scenarios.novartis_qc,
            context: tObj.problems.quality_at_least_4_pass,
            promptLatex: "P(\\\\text{≥4 pass})",
            expressionLatex: "0.95^5 + 5 \\times 0.95^4 \\times 0.05",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.977, unit: "" }],
            correctLatex: "P \\approx 0.977",
          },
          {
            id: "CA3",
            difficulty,
            stage,
            scenario: tObj.scenarios.four_buses,
            context: tObj.problems.four_buses_all_ontime,
            promptLatex: "P(\\\\text{all on time})",
            expressionLatex: "0.8^4",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.41, unit: "" }],
            correctLatex: "P = 0.8^4 \\approx 0.41",
          },
          {
            id: "CA4",
            difficulty,
            stage,
            scenario: tObj.scenarios.weather_basel,
            context: tObj.problems.week_no_rain,
            promptLatex: "P(\\\\text{no rain 7 days})",
            expressionLatex: "0.6^7",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.028, unit: "" }],
            correctLatex: "P = 0.6^7 \\approx 0.028",
          },
          {
            id: "CA5",
            difficulty,
            stage,
            scenario: tObj.scenarios.exam_results,
            context: tObj.problems.five_students_all_pass,
            promptLatex: "P(\\\\text{all 5 pass})",
            expressionLatex: "0.85^5",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.444, unit: "" }],
            correctLatex: "P = 0.85^5 \\approx 0.444",
          },
        ],
        ELITE: [
          {
            id: "CE1",
            difficulty,
            stage,
            scenario: tObj.scenarios.three_events,
            context: tObj.problems.three_coins_two_heads,
            promptLatex: "P(\\\\text{exactly 2 heads})",
            expressionLatex: "\\\\frac{3}{8}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.375, unit: "" }],
            correctLatex: "P = \\\\frac{3}{8} = 0.375 = 37.5\\%",
          },
          {
            id: "CE2",
            difficulty,
            stage,
            scenario: tObj.scenarios.three_events,
            context: tObj.problems.four_coins_exactly_3_heads,
            promptLatex: "P(\\\\text{exactly 3})",
            expressionLatex: "\\\\frac{4}{16}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xx", expected: 0.25, unit: "" }],
            correctLatex: "P = \\\\frac{4}{16} = 0.25",
          },
          {
            id: "CE3",
            difficulty,
            stage,
            scenario: tObj.scenarios.novartis_qc,
            context: tObj.problems.quality_exactly_4_pass,
            promptLatex: "P(\\\\text{exactly 4})",
            expressionLatex: "5 \\times 0.95^4 \\times 0.05",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.204, unit: "" }],
            correctLatex: "P \\approx 0.204",
          },
          {
            id: "CE4",
            difficulty,
            stage,
            scenario: tObj.scenarios.three_events,
            context: tObj.problems.five_coins_at_least_4_heads,
            promptLatex: "P(\\\\text{≥4 heads})",
            expressionLatex: "\\\\frac{6}{32}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxx", expected: 0.188, unit: "" }],
            correctLatex: "P = \\\\frac{6}{32} \\approx 0.188",
          },
          {
            id: "CE5",
            difficulty,
            stage,
            scenario: tObj.scenarios.complex_event,
            context: tObj.problems.birthday_paradox_simple,
            promptLatex: "P(\\\\text{match})",
            expressionLatex: "1 - \\\\frac{365 \\times 364}{365^2}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "P", placeholder: "0.xxxx", expected: 0.0027, unit: "" }],
            correctLatex: "P \\approx 0.0027",
          },
        ],
      },
      DATA_STATS: {
        BASIC: [
          {
            id: "D1",
            difficulty,
            stage,
            scenario: tObj.scenarios.temperature,
            context: tObj.problems.avg_temperature,
            promptLatex: "\\\\text{Average}",
            expressionLatex: "\\\\frac{18+22+20+19+21+23+20}{7}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx.x", expected: 20.4, unit: "°C" }],
            correctLatex: "\\bar{x} \\approx 20.4°C",
          },
          {
            id: "D2",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.simple_average_5,
            promptLatex: "\\\\text{Average}",
            expressionLatex: "\\\\frac{80+85+90+75+95}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 85, unit: "" }],
            correctLatex: "\\bar{x} = 85",
          },
          {
            id: "D3",
            difficulty,
            stage,
            scenario: tObj.scenarios.pocket_money,
            context: tObj.problems.simple_sum,
            promptLatex: "\\\\text{Total}",
            expressionLatex: "40+25+20+15",
            targetLatex: "T",
            slots: [{ id: "T", labelLatex: "T", placeholder: "xxx", expected: 100, unit: "CHF" }],
            correctLatex: "T = 100 \\\\text{ CHF}",
          },
          {
            id: "D4",
            difficulty,
            stage,
            scenario: tObj.scenarios.temperature,
            context: tObj.problems.avg_temperature_5_days,
            promptLatex: "\\\\text{Average}",
            expressionLatex: "\\\\frac{15+18+20+17+20}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 18, unit: "°C" }],
            correctLatex: "\\bar{x} = 18°C",
          },
          {
            id: "D5",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.median_5_values,
            promptLatex: "\\\\text{Median}",
            expressionLatex: "\\\\text{middle of } 10,12,15,18,20",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx", expected: 15, unit: "" }],
            correctLatex: "M = 15",
          },
        ],
        CORE: [
          {
            id: "D6",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.class_average,
            promptLatex: "\\\\text{Class Average}",
            expressionLatex: "\\\\frac{\\sum scores}{n}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 78, unit: "" }],
            correctLatex: "\\bar{x} = 78",
          },
          {
            id: "D7",
            difficulty,
            stage,
            scenario: tObj.scenarios.pocket_money,
            context: tObj.problems.spending_analysis,
            promptLatex: "\\\\text{Food %}",
            expressionLatex: "\\\\frac{40}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "\\%", placeholder: "xx", expected: 40, unit: "%" }],
            correctLatex: "40\\%",
          },
          {
            id: "D8",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.median_even_count,
            promptLatex: "\\\\text{Median}",
            expressionLatex: "\\\\frac{75+80}{2}",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx.x", expected: 77.5, unit: "" }],
            correctLatex: "M = 77.5",
          },
          {
            id: "D9",
            difficulty,
            stage,
            scenario: tObj.scenarios.temperature,
            context: tObj.problems.range_calculation,
            promptLatex: "\\\\text{Range}",
            expressionLatex: "23 - 15",
            targetLatex: "R",
            slots: [{ id: "R", labelLatex: "R", placeholder: "x", expected: 8, unit: "°C" }],
            correctLatex: "R = 8°C",
          },
          {
            id: "D10",
            difficulty,
            stage,
            scenario: tObj.scenarios.pocket_money,
            context: tObj.problems.percentage_transport,
            promptLatex: "\\\\text{Transport %}",
            expressionLatex: "\\\\frac{25}{100}",
            targetLatex: "P",
            slots: [{ id: "P", labelLatex: "\\%", placeholder: "xx", expected: 25, unit: "%" }],
            correctLatex: "25\\%",
          },
        ],
        ADVANCED: [
          {
            id: "D11",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.weighted_average,
            promptLatex: "\\\\text{Weighted Avg}",
            expressionLatex: "\\\\frac{80 \\times 2 + 90 \\times 3}{5}",
            targetLatex: "\\bar{x}_w",
            slots: [{ id: "avg", labelLatex: "\\bar{x}_w", placeholder: "xx", expected: 86, unit: "" }],
            correctLatex: "\\bar{x}_w = 86",
          },
          {
            id: "D12",
            difficulty,
            stage,
            scenario: tObj.scenarios.data_comparison,
            context: tObj.problems.median_vs_mean,
            promptLatex: "\\\\text{Median}",
            expressionLatex: "\\\\text{middle value}",
            targetLatex: "M",
            slots: [{ id: "M", labelLatex: "M", placeholder: "xx", expected: 15, unit: "" }],
            correctLatex: "M = 15",
          },
          {
            id: "D13",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.mode_calculation,
            promptLatex: "\\\\text{Mode}",
            expressionLatex: "\\\\text{most frequent}",
            targetLatex: "Mo",
            slots: [{ id: "Mo", labelLatex: "Mo", placeholder: "xx", expected: 85, unit: "" }],
            correctLatex: "Mo = 85",
          },
          {
            id: "D14",
            difficulty,
            stage,
            scenario: tObj.scenarios.pocket_money,
            context: tObj.problems.budget_remaining,
            promptLatex: "\\\\text{Remaining}",
            expressionLatex: "100 - 40 - 25 - 20",
            targetLatex: "R",
            slots: [{ id: "R", labelLatex: "R", placeholder: "xx", expected: 15, unit: "CHF" }],
            correctLatex: "R = 15 \\\\text{ CHF}",
          },
          {
            id: "D15",
            difficulty,
            stage,
            scenario: tObj.scenarios.temperature,
            context: tObj.problems.quartile_calculation,
            promptLatex: "\\\\text{Q1}",
            expressionLatex: "\\\\text{25th percentile}",
            targetLatex: "Q_1",
            slots: [{ id: "Q1", labelLatex: "Q_1", placeholder: "xx", expected: 17, unit: "°C" }],
            correctLatex: "Q_1 = 17°C",
          },
        ],
        ELITE: [
          {
            id: "D16",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.standard_deviation_simple,
            promptLatex: "\\\\text{Variance}",
            expressionLatex: "\\\\frac{\\sum(x_i - \\bar{x})^2}{n}",
            targetLatex: "\\sigma^2",
            slots: [{ id: "var", labelLatex: "\\sigma^2", placeholder: "xx", expected: 50, unit: "" }],
            correctLatex: "\\sigma^2 = 50",
          },
          {
            id: "D17",
            difficulty,
            stage,
            scenario: tObj.scenarios.data_comparison,
            context: tObj.problems.outlier_effect,
            promptLatex: "\\\\text{New Mean}",
            expressionLatex: "\\\\frac{10+12+15+18+100}{5}",
            targetLatex: "\\bar{x}",
            slots: [{ id: "avg", labelLatex: "\\bar{x}", placeholder: "xx", expected: 31, unit: "" }],
            correctLatex: "\\bar{x} = 31",
          },
          {
            id: "D18",
            difficulty,
            stage,
            scenario: tObj.scenarios.test_scores,
            context: tObj.problems.interquartile_range,
            promptLatex: "\\\\text{IQR}",
            expressionLatex: "Q_3 - Q_1",
            targetLatex: "IQR",
            slots: [{ id: "IQR", labelLatex: "IQR", placeholder: "xx", expected: 10, unit: "" }],
            correctLatex: "IQR = 10",
          },
          {
            id: "D19",
            difficulty,
            stage,
            scenario: tObj.scenarios.pocket_money,
            context: tObj.problems.percentage_change,
            promptLatex: "\\\\text{% Change}",
            expressionLatex: "\\\\frac{120-100}{100} \\times 100",
            targetLatex: "\\Delta\\%",
            slots: [{ id: "pct", labelLatex: "\\Delta\\%", placeholder: "xx", expected: 20, unit: "%" }],
            correctLatex: "\\Delta\\% = 20\\%",
          },
          {
            id: "D20",
            difficulty,
            stage,
            scenario: tObj.scenarios.data_comparison,
            context: tObj.problems.correlation_direction,
            promptLatex: "\\\\text{Correlation}",
            expressionLatex: "\\\\text{positive/negative}",
            targetLatex: "r",
            slots: [{ id: "r", labelLatex: "r", placeholder: "1 or -1", expected: 1, unit: "" }],
            correctLatex: "r > 0 \\\\text{ (positive)}",
          },
        ],
      },
    };

    return pools[stage][difficulty] || [];
  }, []);

  const buildPool = useCallback((difficulty: Difficulty, stage: Stage) => buildStagePool(sm2_08_t, difficulty, stage), [sm2_08_t]);

  const {
    currentQuest: quest,
    stage,
    inputs,
    setInputs,
    lastCheck,
    verify,
    next,
    handleStageChange,
    difficulty,
    handleDifficultyChange,
  } = useQuestManager<ProbQuest, Stage>({
    buildPool,
    initialStage: "BASIC_PROB",
    tolerance: 0.01,
  });

  useEffect(() => {
    if (lastCheck?.ok) {
      completeStage("sm2-08", stage);
    }
  }, [lastCheck, completeStage, stage]);

  return (
    <ChamberLayout
      title={t("sm2_08.title")}
      moduleCode="SM2.08"
      difficulty={difficulty}
      onDifficultyChange={handleDifficultyChange}
      stages={[
        { id: "BASIC_PROB", label: t("sm2_08.stages.basic_prob") },
        { id: "LOTTERY", label: t("sm2_08.stages.lottery") },
        { id: "COMBINED", label: t("sm2_08.stages.combined") },
        { id: "DATA_STATS", label: t("sm2_08.stages.data_stats") },
      ]}
      currentStage={stage}
      onStageChange={(s) => handleStageChange(s as Stage)}
      onVerify={verify}
      onNext={next}
      checkStatus={lastCheck}
      footerLeft={t("sm2_08.footer_left")}
      translations={{
        back: t("sm2_08.back"),
        check: t("sm2_08.check"),
        next: t("sm2_08.next"),
        correct: t("sm2_08.correct"),
        incorrect: t("sm2_08.incorrect"),
        ready: t("sm2_08.ready"),
        monitor_title: t("sm2_08.monitor_title"),
        difficulty: {
          basic: t("sm2_08.difficulty.basic"),
          core: t("sm2_08.difficulty.core"),
          advanced: t("sm2_08.difficulty.advanced"),
          elite: t("sm2_08.difficulty.elite"),
        },
      }}
      monitorContent={
        <div className="space-y-4">
          <ProbabilityVisualizer stage={stage} language={currentLanguage as "EN" | "CN" | "DE"} />
          <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black">
            {t("sm2_08.formula_title")}
          </div>
          <div className="rounded-xl border border-cyan-500/30 bg-black/50 p-4">
            <BlockMath math="P(E) = \frac{\text{favorable outcomes}}{\text{total outcomes}}" />
          </div>
        </div>
      }
    >
      <div className="space-y-8">
        {quest?.scenario && (
          <div className="p-6 bg-purple-500/10 border border-purple-500/30 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-purple-400 font-black mb-3">
              {t("sm2_08.basel_scenario")}
            </div>
            <p className="text-white/90 leading-relaxed font-medium">{quest.scenario}</p>
          </div>
        )}

        {quest?.context && (
          <div className="p-6 bg-cyan-500/5 border border-cyan-500/20 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black mb-3">
              {t("sm2_08.scenario_title")}
            </div>
            <p className="text-white/80 leading-relaxed">{quest.context}</p>
          </div>
        )}

        <div className="text-center space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white/60 font-black">
            {t("sm2_08.calculate_title")}
          </div>
          <div className="text-3xl text-white font-black">
            <InlineMath math={quest?.promptLatex || ""} />
          </div>
        </div>

        {quest?.expressionLatex && (
          <div className="text-center p-4 bg-white/5 border border-white/10 rounded-xl">
            <BlockMath math={quest.expressionLatex} />
          </div>
        )}

        <div className="max-w-md mx-auto space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white font-black text-center">
            {t("sm2_08.answer_title")}
          </div>
          {quest?.slots.map((slot) => (
            <div key={slot.id} className="space-y-2">
              <label className="text-sm text-white/70 font-mono">
                <InlineMath math={slot.labelLatex} />
              </label>
              <input
                value={inputs[slot.id] ?? ""}
                onChange={(e) => setInputs((prev) => ({ ...prev, [slot.id]: e.target.value }))}
                className="w-full bg-black border-2 border-cyan-500/50 p-4 text-center outline-none focus:border-cyan-400 placeholder:text-white/40 font-black text-2xl text-white rounded-lg"
                placeholder={slot.placeholder}
              />
            </div>
          ))}
        </div>

        {lastCheck?.ok && quest?.correctLatex && (
          <div className="text-center p-4 bg-green-500/10 border border-green-500/30 rounded-xl">
            <div className="text-green-400 font-black mb-2">{t("sm2_08.solution_title")}</div>
            <BlockMath math={quest.correctLatex} />
          </div>
        )}
      </div>
    </ChamberLayout>
  );
}
