"use client";

import { useEffect, useCallback, useMemo } from "react";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";
import { useAppStore } from "@/lib/store";
import { useLanguage } from "@/lib/i18n";
import ChamberLayout from "@/components/layout/ChamberLayout";
import EquationBalance from "@/components/chamber/sm1-04/EquationBalance";
import { Difficulty, Quest, useQuestManager } from "@/hooks/useQuestManager";
import { renderMixedText } from "@/lib/latex-utils";

type Stage = "BALANCE" | "SOLVE" | "TRANSFORM" | "APPLICATIONS";
type EquationQuest = Quest & {
  stage: Stage;
  context?: string;
  scenario?: string;
  equation?: string;
  leftSide?: number;
  rightSide?: number;
  operation?: string;
};

export default function SM104Page() {
  const { completeStage } = useAppStore();
  const { t } = useLanguage();

  // Pre-extract all translations
  const sm1_04_t = useMemo(() => ({
    objective_title: t("sm1_04.objective_title"),
    scenario_title: t("sm1_04.scenario_title"),
    labels: {
      current_age: t("sm1_04.labels.current_age"),
      years: t("sm1_04.labels.years"),
      pure_acid: t("sm1_04.labels.pure_acid"),
      liters: t("sm1_04.labels.liters"),
      boat_speed: t("sm1_04.labels.boat_speed"),
      speed_unit: t("sm1_04.labels.speed_unit"),
      cost_price: t("sm1_04.labels.cost_price"),
      currency: t("sm1_04.labels.currency"),
      left: t("sm1_04.labels.left_side"),
      right: t("sm1_04.labels.right_side"),
      operation: t("sm1_04.labels.operation"),
      step1: t("sm1_04.labels.identify_eq"),
      step2: t("sm1_04.labels.isolate_var"),
      step3: t("sm1_04.labels.solve_for").replace("{var}", "x"),
      bus: t("sm1_04.labels.bus"),
      ferry: t("sm1_04.labels.ferry"),
      apps: t("sm1_04.labels.apps"),
      model: t("sm1_04.labels.model"),
      steps_solve: t("sm1_04.labels.steps_solve"),
      steps_trans: t("sm1_04.labels.steps_trans"),
      problems: t("sm1_04.labels.problems"),
      min: t("sm1_04.labels.min"),
      km: t("sm1_04.labels.km"),
      samples: t("sm1_04.labels.samples"),
      m: t("sm1_04.labels.m"),
      hours: t("sm1_04.labels.hours"),
      percent: t("sm1_04.labels.percent"),
      ticket_price: t("sm1_04.labels.ticket_price"),
      ferry_time: t("sm1_04.labels.ferry_time"),
      age: t("sm1_04.labels.age"),
      distance: t("sm1_04.labels.distance"),
      original_price: t("sm1_04.labels.original_price"),
      adult_tickets: t("sm1_04.labels.adult_tickets"),
      samples_per_box: t("sm1_04.labels.samples_per_box"),
      width: t("sm1_04.labels.width"),
      speed: t("sm1_04.labels.speed"),
      original_concentration: t("sm1_04.labels.original_concentration"),
      first_number: t("sm1_04.labels.first_number"),
      hours_worker: t("sm1_04.labels.hours_worker"),
      liters_solution: t("sm1_04.labels.liters_solution"),
      principal_amount: t("sm1_04.labels.principal_amount"),
      time_to_meet: t("sm1_04.labels.time_to_meet")
    },
    scenarios: {
      applications: t("sm1_04.scenarios.applications"),
      balance: t("sm1_04.scenarios.balance"),
      solve: t("sm1_04.scenarios.solve"),
      transform: t("sm1_04.scenarios.transform"),
    },
    problems: {
      app_age_ratio: t("sm1_04.problems.app_age_ratio"),
      app_age_simple: t("sm1_04.problems.app_age_simple"),
      app_age_sum: t("sm1_04.problems.app_age_sum"),
      app_boat_current: t("sm1_04.problems.app_boat_current"),
      app_bus_ticket: t("sm1_04.problems.app_bus_ticket"),
      app_compound_mixture: t("sm1_04.problems.app_compound_mixture"),
      app_consecutive_numbers: t("sm1_04.problems.app_consecutive_numbers"),
      app_distance_simple: t("sm1_04.problems.app_distance_simple"),
      app_investment_interest: t("sm1_04.problems.app_investment_interest"),
      app_mixture_problem: t("sm1_04.problems.app_mixture_problem"),
      app_novartis_samples: t("sm1_04.problems.app_novartis_samples"),
      app_price_discount: t("sm1_04.problems.app_price_discount"),
      app_profit_loss: t("sm1_04.problems.app_profit_loss"),
      app_rectangle_perimeter: t("sm1_04.problems.app_rectangle_perimeter"),
      app_rhine_time: t("sm1_04.problems.app_rhine_time"),
      app_roche_concentration: t("sm1_04.problems.app_roche_concentration"),
      app_speed_distance: t("sm1_04.problems.app_speed_distance"),
      app_train_meeting: t("sm1_04.problems.app_train_meeting"),
      app_tram_tickets: t("sm1_04.problems.app_tram_tickets"),
      app_work_rate: t("sm1_04.problems.app_work_rate"),
      bal_add_both: t("sm1_04.problems.bal_add_both"),
      bal_both_sides_x: t("sm1_04.problems.bal_both_sides_x"),
      bal_complex_both: t("sm1_04.problems.bal_complex_both"),
      bal_complex_distribute: t("sm1_04.problems.bal_complex_distribute"),
      bal_decimal_coeff: t("sm1_04.problems.bal_decimal_coeff"),
      bal_distribute: t("sm1_04.problems.bal_distribute"),
      bal_divide_both: t("sm1_04.problems.bal_divide_both"),
      bal_fraction_coeff: t("sm1_04.problems.bal_fraction_coeff"),
      bal_fractions: t("sm1_04.problems.bal_fractions"),
      bal_multiply_both: t("sm1_04.problems.bal_multiply_both"),
      bal_negative_coeff: t("sm1_04.problems.bal_negative_coeff"),
      bal_negative_result: t("sm1_04.problems.bal_negative_result"),
      bal_nested_parens: t("sm1_04.problems.bal_nested_parens"),
      bal_parentheses_both: t("sm1_04.problems.bal_parentheses_both"),
      bal_proportion: t("sm1_04.problems.bal_proportion"),
      bal_reciprocal: t("sm1_04.problems.bal_reciprocal"),
      bal_simple_check: t("sm1_04.problems.bal_simple_check"),
      bal_subtract_both: t("sm1_04.problems.bal_subtract_both"),
      bal_three_fractions: t("sm1_04.problems.bal_three_fractions"),
      bal_two_steps: t("sm1_04.problems.bal_two_steps"),
      sol_combine_like: t("sm1_04.problems.sol_combine_like"),
      sol_complex_distribute: t("sm1_04.problems.sol_complex_distribute"),
      sol_decimal_coeff: t("sm1_04.problems.sol_decimal_coeff"),
      sol_decimal_complex: t("sm1_04.problems.sol_decimal_complex"),
      sol_distribute_simple: t("sm1_04.problems.sol_distribute_simple"),
      sol_fraction_both: t("sm1_04.problems.sol_fraction_both"),
      sol_fraction_result: t("sm1_04.problems.sol_fraction_result"),
      sol_negative_both: t("sm1_04.problems.sol_negative_both"),
      sol_negative_coeff: t("sm1_04.problems.sol_negative_coeff"),
      sol_negative_simple: t("sm1_04.problems.sol_negative_simple"),
      sol_nested_parens: t("sm1_04.problems.sol_nested_parens"),
      sol_one_step_add: t("sm1_04.problems.sol_one_step_add"),
      sol_one_step_div: t("sm1_04.problems.sol_one_step_div"),
      sol_one_step_mult: t("sm1_04.problems.sol_one_step_mult"),
      sol_one_step_sub: t("sm1_04.problems.sol_one_step_sub"),
      sol_proportion_eq: t("sm1_04.problems.sol_proportion_eq"),
      sol_three_terms: t("sm1_04.problems.sol_three_terms"),
      sol_two_step_1: t("sm1_04.problems.sol_two_step_1"),
      sol_two_step_2: t("sm1_04.problems.sol_two_step_2"),
      sol_x_both_sides: t("sm1_04.problems.sol_x_both_sides"),
      tra_both_expand: t("sm1_04.problems.tra_both_expand"),
      tra_collect_terms: t("sm1_04.problems.tra_collect_terms"),
      tra_complex_collect: t("sm1_04.problems.tra_complex_collect"),
      tra_decimal_expand: t("sm1_04.problems.tra_decimal_expand"),
      tra_double_expand: t("sm1_04.problems.tra_double_expand"),
      tra_expand_first: t("sm1_04.problems.tra_expand_first"),
      tra_fraction_clear: t("sm1_04.problems.tra_fraction_clear"),
      tra_fractions_lcd: t("sm1_04.problems.tra_fractions_lcd"),
      tra_isolate_x: t("sm1_04.problems.tra_isolate_x"),
      tra_mixed_complex: t("sm1_04.problems.tra_mixed_complex"),
      tra_move_both: t("sm1_04.problems.tra_move_both"),
      tra_move_constant: t("sm1_04.problems.tra_move_constant"),
      tra_move_variable: t("sm1_04.problems.tra_move_variable"),
      tra_multi_step: t("sm1_04.problems.tra_multi_step"),
      tra_negative_coeff: t("sm1_04.problems.tra_negative_coeff"),
      tra_negative_move: t("sm1_04.problems.tra_negative_move"),
      tra_nested_complex: t("sm1_04.problems.tra_nested_complex"),
      tra_proportion_cross: t("sm1_04.problems.tra_proportion_cross"),
      tra_three_fractions: t("sm1_04.problems.tra_three_fractions"),
      tra_two_moves: t("sm1_04.problems.tra_two_moves"),
    },
  }), [t]);

  const buildStagePool = useCallback((tObj: typeof sm1_04_t, difficulty: Difficulty, stage: Stage): EquationQuest[] => {
    const pools: Record<Stage, Record<Difficulty, EquationQuest[]>> = {
      BALANCE: {
        BASIC: [
          {
            id: "BAL_B1",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_add_both,
            promptLatex: t("sm1_04.prompts.bal_b1"),
            expressionLatex: "x + 3 + 2 = 7 + 2",
            targetLatex: "x",
            equation: "x + 3 = 7",
            operation: "+2",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_B2",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_subtract_both,
            promptLatex: t("sm1_04.prompts.bal_b2"),
            expressionLatex: "x + 5 - 5 = 8 - 5",
            targetLatex: "x",
            equation: "x + 5 = 8",
            operation: "-5",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_B3",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_multiply_both,
            promptLatex: t("sm1_04.prompts.bal_b3"),
            expressionLatex: "\\frac{x}{2} \\times 2 = 4 \\times 2",
            targetLatex: "x",
            equation: "x/2 = 4",
            operation: "×2",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "BAL_B4",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_divide_both,
            promptLatex: t("sm1_04.prompts.bal_b4"),
            expressionLatex: "\\frac{2x}{2} = \\frac{10}{2}",
            targetLatex: "x",
            equation: "2x = 10",
            operation: "÷2",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "BAL_B5",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_simple_check,
            promptLatex: t("sm1_04.prompts.bal_b5"),
            expressionLatex: "x = 6 - 2",
            targetLatex: "x",
            equation: "x + 2 = 6",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        CORE: [
          {
            id: "BAL_C1",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_two_steps,
            promptLatex: t("sm1_04.prompts.bal_c1"),
            expressionLatex: "2x = 11 - 3, \\quad x = \\frac{8}{2}",
            targetLatex: "x",
            equation: "2x + 3 = 11",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_C2",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_negative_result,
            promptLatex: t("sm1_04.prompts.bal_c2"),
            expressionLatex: "x = 3 - 7",
            targetLatex: "x",
            equation: "x + 7 = 3",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.minus_x"), expected: -4, unit: "" }],
            correctLatex: "x = -4",
          },
          {
            id: "BAL_C3",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_fraction_coeff,
            promptLatex: t("sm1_04.prompts.bal_c3"),
            expressionLatex: "\\frac{x}{3} = 3, \\quad x = 9",
            targetLatex: "x",
            equation: "x/3 + 2 = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 9, unit: "" }],
            correctLatex: "x = 9",
          },
          {
            id: "BAL_C4",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_both_sides_x,
            promptLatex: t("sm1_04.prompts.bal_c4"),
            expressionLatex: "5 = 2x - x",
            targetLatex: "x",
            equation: "x + 5 = 2x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "BAL_C5",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_distribute,
            promptLatex: t("sm1_04.prompts.bal_c5"),
            expressionLatex: "3x + 6 = 15, \\quad 3x = 9",
            targetLatex: "x",
            equation: "3(x + 2) = 15",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
        ],
        ADVANCED: [
          {
            id: "BAL_A1",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_complex_both,
            promptLatex: t("sm1_04.prompts.bal_a1"),
            expressionLatex: "2x - x = 7 - 3",
            targetLatex: "x",
            equation: "2x + 3 = x + 7",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_A2",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_fractions,
            promptLatex: t("sm1_04.prompts.bal_a2"),
            expressionLatex: "\\frac{3x + 2x}{6} = 5, \\quad 5x = 30",
            targetLatex: "x",
            equation: "x/2 + x/3 = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "BAL_A3",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_parentheses_both,
            promptLatex: t("sm1_04.prompts.bal_a3"),
            expressionLatex: "2x + 2 = 3x - 6, \\quad x = 8",
            targetLatex: "x",
            equation: "2(x + 1) = 3(x - 2)",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "BAL_A4",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_decimal_coeff,
            promptLatex: t("sm1_04.prompts.bal_a4"),
            expressionLatex: "0.5x = 1.5, \\quad x = 3",
            targetLatex: "x",
            equation: "0.5x + 1.5 = 3",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_A5",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_negative_coeff,
            promptLatex: t("sm1_04.prompts.bal_a5"),
            expressionLatex: "-2x = -8, \\quad x = 4",
            targetLatex: "x",
            equation: "-2x + 5 = -3",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        ELITE: [
          {
            id: "BAL_E1",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_nested_parens,
            promptLatex: t("sm1_04.prompts.bal_e1"),
            expressionLatex: "2(2x - 1) = 10, \\quad 4x - 2 = 10",
            targetLatex: "x",
            equation: "2(3x - (x + 1)) = 10",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_E2",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_three_fractions,
            promptLatex: t("sm1_04.prompts.bal_e2"),
            expressionLatex: "\\frac{3x - 2x + x}{6} = 2, \\quad 2x = 12",
            targetLatex: "x",
            equation: "x/2 - x/3 + x/6 = 2",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "BAL_E3",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_complex_distribute,
            promptLatex: t("sm1_04.prompts.bal_e3"),
            expressionLatex: "6x - 3 - 2x - 6 = 5, \\quad 4x = 14",
            targetLatex: "x",
            equation: "3(2x - 1) - 2(x + 3) = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_x"), expected: 3.5, unit: "" }],
            correctLatex: "x = 3.5",
          },
          {
            id: "BAL_E4",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_reciprocal,
            promptLatex: t("sm1_04.prompts.bal_e4"),
            expressionLatex: "\\frac{2 + 1}{2x} = \\frac{3}{4}, \\quad x = 2",
            targetLatex: "x",
            equation: "1/x + 1/(2x) = 3/4",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 2, unit: "" }],
            correctLatex: "x = 2",
          },
          {
            id: "BAL_E5",
            difficulty,
            stage,
            scenario: tObj.scenarios.balance,
            context: tObj.problems.bal_proportion,
            promptLatex: t("sm1_04.prompts.bal_e5"),
            expressionLatex: "x + 1 = 2(x - 1), \\quad x = 3",
            targetLatex: "x",
            equation: "(x + 1)/(x - 1) = 2",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
        ],
      },
      SOLVE: {
        BASIC: [
          {
            id: "SOL_B1",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_one_step_add,
            promptLatex: t("sm1_04.prompts.sol_b1"),
            expressionLatex: "x = 7 - 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_B2",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_one_step_sub,
            promptLatex: t("sm1_04.prompts.sol_b2"),
            expressionLatex: "x = 2 + 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 7, unit: "" }],
            correctLatex: "x = 7",
          },
          {
            id: "SOL_B3",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_one_step_mult,
            promptLatex: t("sm1_04.prompts.sol_b3"),
            expressionLatex: "x = \\frac{12}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_B4",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_one_step_div,
            promptLatex: t("sm1_04.prompts.sol_b4"),
            expressionLatex: "x = 3 \\times 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "SOL_B5",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_negative_simple,
            promptLatex: t("sm1_04.prompts.sol_b5"),
            expressionLatex: "x = 3 - 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.minus_x"), expected: -5, unit: "" }],
            correctLatex: "x = -5",
          },
        ],
        CORE: [
          {
            id: "SOL_C1",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_two_step_1,
            promptLatex: t("sm1_04.prompts.sol_c1"),
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_C2",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_two_step_2,
            promptLatex: t("sm1_04.prompts.sol_c2"),
            expressionLatex: "\\frac{x}{3} = 6, \\quad x = 18",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 18, unit: "" }],
            correctLatex: "x = 18",
          },
          {
            id: "SOL_C3",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_negative_coeff,
            promptLatex: t("sm1_04.prompts.sol_c3"),
            expressionLatex: "x = \\frac{15}{-3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.minus_x"), expected: -5, unit: "" }],
            correctLatex: "x = -5",
          },
          {
            id: "SOL_C4",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_fraction_result,
            promptLatex: t("sm1_04.prompts.sol_c4"),
            expressionLatex: "2x = 3, \\quad x = 1.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_x"), expected: 1.5, unit: "" }],
            correctLatex: "x = 1.5",
          },
          {
            id: "SOL_C5",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_decimal_coeff,
            promptLatex: t("sm1_04.prompts.sol_c5"),
            expressionLatex: "x = \\frac{4}{0.5}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
        ],
        ADVANCED: [
          {
            id: "SOL_A1",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_combine_like,
            promptLatex: t("sm1_04.prompts.sol_a1"),
            expressionLatex: "5x = 15, \\quad x = 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "SOL_A2",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_distribute_simple,
            promptLatex: t("sm1_04.prompts.sol_a2"),
            expressionLatex: "2x + 6 = 14, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_A3",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_x_both_sides,
            promptLatex: t("sm1_04.prompts.sol_a3"),
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_A4",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_fraction_both,
            promptLatex: t("sm1_04.prompts.sol_a4"),
            expressionLatex: "\\frac{3x}{4} = 6, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "SOL_A5",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_negative_both,
            promptLatex: t("sm1_04.prompts.sol_a5"),
            expressionLatex: "-x = -8, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
        ],
        ELITE: [
          {
            id: "SOL_E1",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_complex_distribute,
            promptLatex: t("sm1_04.prompts.sol_e1"),
            expressionLatex: "6x - 3 = 2x + 10, \\quad x = 3.25",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_xx"), expected: 3.25, unit: "" }],
            correctLatex: "x = 3.25",
          },
          {
            id: "SOL_E2",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_nested_parens,
            promptLatex: t("sm1_04.prompts.sol_e2"),
            expressionLatex: "2(2x - 3) = 10, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_E3",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_three_terms,
            promptLatex: t("sm1_04.prompts.sol_e3"),
            expressionLatex: "\\frac{2x}{3} = 4, \\quad x = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "SOL_E4",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_decimal_complex,
            promptLatex: t("sm1_04.prompts.sol_e4"),
            expressionLatex: "0.8x - 1 = 2.6, \\quad x = 4.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_x"), expected: 4.5, unit: "" }],
            correctLatex: "x = 4.5",
          },
          {
            id: "SOL_E5",
            difficulty,
            stage,
            scenario: tObj.scenarios.solve,
            context: tObj.problems.sol_proportion_eq,
            promptLatex: t("sm1_04.prompts.sol_e5"),
            expressionLatex: "5(x - 2) = 3(x + 1), \\quad x = 6.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_x"), expected: 6.5, unit: "" }],
            correctLatex: "x = 6.5",
          },
        ],
      },
      TRANSFORM: {
        BASIC: [
          {
            id: "TRA_B1",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_move_constant,
            promptLatex: t("sm1_04.prompts.tra_b1"),
            expressionLatex: "x = 12 - 7",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B2",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_move_variable,
            promptLatex: t("sm1_04.prompts.tra_b2"),
            expressionLatex: "2x - x = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B3",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_isolate_x,
            promptLatex: t("sm1_04.prompts.tra_b3"),
            expressionLatex: "x = \\frac{15}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B4",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_two_moves,
            promptLatex: t("sm1_04.prompts.tra_b4"),
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_B5",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_negative_move,
            promptLatex: t("sm1_04.prompts.tra_b5"),
            expressionLatex: "x = -2 + 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        CORE: [
          {
            id: "TRA_C1",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_collect_terms,
            promptLatex: t("sm1_04.prompts.tra_c1"),
            expressionLatex: "5x = 20, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C2",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_move_both,
            promptLatex: t("sm1_04.prompts.tra_c2"),
            expressionLatex: "4x - 2x = 11 - 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C3",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_expand_first,
            promptLatex: t("sm1_04.prompts.tra_c3"),
            expressionLatex: "2x + 6 = 14, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C4",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_fraction_clear,
            promptLatex: t("sm1_04.prompts.tra_c4"),
            expressionLatex: "\\frac{x}{3} = 3, \\quad x = 9",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 9, unit: "" }],
            correctLatex: "x = 9",
          },
          {
            id: "TRA_C5",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_negative_coeff,
            promptLatex: t("sm1_04.prompts.tra_c5"),
            expressionLatex: "-2x = -4, \\quad x = 2",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 2, unit: "" }],
            correctLatex: "x = 2",
          },
        ],
        ADVANCED: [
          {
            id: "TRA_A1",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_multi_step,
            promptLatex: t("sm1_04.prompts.tra_a1"),
            expressionLatex: "3x - 6 + 2x = 19, \\quad 5x = 25",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_A2",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_both_expand,
            promptLatex: t("sm1_04.prompts.tra_a2"),
            expressionLatex: "2x + 2 = 3x - 6, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "TRA_A3",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_fractions_lcd,
            promptLatex: t("sm1_04.prompts.tra_a3"),
            expressionLatex: "\\frac{5x}{6} = 10, \\quad x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "TRA_A4",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_decimal_expand,
            promptLatex: t("sm1_04.prompts.tra_a4"),
            expressionLatex: "0.5x + 2 = 3.5, \\quad x = 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "TRA_A5",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_complex_collect,
            promptLatex: t("sm1_04.prompts.tra_a5"),
            expressionLatex: "5x - 2x + 6 = 18, \\quad 3x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        ELITE: [
          {
            id: "TRA_E1",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_nested_complex,
            promptLatex: t("sm1_04.prompts.tra_e1"),
            expressionLatex: "3(x - 1) = 15, \\quad x = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "TRA_E2",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_three_fractions,
            promptLatex: t("sm1_04.prompts.tra_e2"),
            expressionLatex: "\\frac{5x}{12} = 5, \\quad x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "TRA_E3",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_double_expand,
            promptLatex: t("sm1_04.prompts.tra_e3"),
            expressionLatex: "6x - 2 - 3x - 6 = 7, \\quad 3x = 15",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_E4",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_proportion_cross,
            promptLatex: t("sm1_04.prompts.tra_e4"),
            expressionLatex: "2(2x + 1) = 3(x - 2), \\quad x = -8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.minus_x"), expected: -8, unit: "" }],
            correctLatex: "x = -8",
          },
          {
            id: "TRA_E5",
            difficulty,
            stage,
            scenario: tObj.scenarios.transform,
            context: tObj.problems.tra_mixed_complex,
            promptLatex: t("sm1_04.prompts.tra_e5"),
            expressionLatex: "2x - 1 + \\frac{x}{3} = 7, \\quad x = 3.6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x_dot_x"), expected: 3.6, unit: "" }],
            correctLatex: "x = 3.6",
          },
        ],
      },
      APPLICATIONS: {
        BASIC: [
          {
            id: "APP_B1",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_bus_ticket,
            promptLatex: t("sm1_04.prompts.app_b1"),
            expressionLatex: "x + 2 = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "CHF" }],
            correctLatex: `x = 3 \\text{ ${tObj.labels.currency}}`,
          },
          {
            id: "APP_B2",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_rhine_time,
            promptLatex: t("sm1_04.prompts.app_b2"),
            expressionLatex: "2x = 10",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 5, unit: "min" }],
            correctLatex: `x = 5 \\text{ ${tObj.labels.min}}`,
          },
          {
            id: "APP_B3",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_age_simple,
            promptLatex: t("sm1_04.prompts.app_b3"),
            expressionLatex: "x + 5 = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 7, unit: "years" }],
            correctLatex: `x = 7 \\text{ ${tObj.labels.years}}`,
          },
          {
            id: "APP_B4",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_distance_simple,
            promptLatex: t("sm1_04.prompts.app_b4"),
            expressionLatex: "\\frac{x}{2} = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 12, unit: "km" }],
            correctLatex: `x = 12 \\text{ ${tObj.labels.km}}`,
          },
          {
            id: "APP_B5",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_price_discount,
            promptLatex: t("sm1_04.prompts.app_b5"),
            expressionLatex: "x - 10 = 40",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 50, unit: "CHF" }],
            correctLatex: `x = 50 \\text{ ${tObj.labels.currency}}`,
          },
        ],
        CORE: [
          {
            id: "APP_C1",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_tram_tickets,
            promptLatex: t("sm1_04.prompts.app_c1"),
            expressionLatex: "3x + 2 \\times 2 = 13",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "CHF" }],
            correctLatex: `x = 3 \\text{ ${tObj.labels.currency}}`,
          },
          {
            id: "APP_C2",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_novartis_samples,
            promptLatex: t("sm1_04.prompts.app_c2"),
            expressionLatex: "5x + 10 = 60",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 10, unit: "" }],
            correctLatex: `x = 10 \\text{ ${tObj.labels.samples}}`,
          },
          {
            id: "APP_C3",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_age_sum,
            promptLatex: t("sm1_04.prompts.s_age"),
            expressionLatex: "x + (x + 30) = 50",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 10, unit: "years" }],
            correctLatex: `x = 10 \\text{ ${tObj.labels.years}}`,
          },
          {
            id: "APP_C4",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_rectangle_perimeter,
            promptLatex: t("sm1_04.prompts.app_c4"),
            expressionLatex: "2(x + 8) = 28",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 6, unit: "m" }],
            correctLatex: `x = 6 \\text{ ${tObj.labels.m}}`,
          },
          {
            id: "APP_C5",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_speed_distance,
            promptLatex: t("sm1_04.prompts.app_c5"),
            expressionLatex: "2x = 80",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 40, unit: "km/h" }],
            correctLatex: `x = 40 \\text{ ${tObj.labels.speed_unit}}`,
          },
        ],
        ADVANCED: [
          {
            id: "APP_A1",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_roche_concentration,
            promptLatex: t("sm1_04.prompts.app_a1"),
            expressionLatex: "0.5x + 0.3 \\times 100 = 0.4 \\times 150",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 60, unit: "%" }],
            correctLatex: "x = 60\\%",
          },
          {
            id: "APP_A2",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_consecutive_numbers,
            promptLatex: t("sm1_04.prompts.app_a2"),
            expressionLatex: "x + (x + 1) + (x + 2) = 48",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 15, unit: "" }],
            correctLatex: "x = 15",
          },
          {
            id: "APP_A3",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_work_rate,
            promptLatex: t("sm1_04.prompts.app_a3"),
            expressionLatex: "\\frac{1}{x} + \\frac{1}{6} = \\frac{1}{2}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 3, unit: "hours" }],
            correctLatex: `x = 3 \\text{ ${tObj.labels.hours}}`,
          },
          {
            id: "APP_A4",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_mixture_problem,
            promptLatex: t("sm1_04.prompts.app_a4"),
            expressionLatex: "0.2x + 0.5 \\times 10 = 0.3(x + 10)",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 20, unit: "L" }],
            correctLatex: `x = 20 \\text{ ${tObj.labels.liters}}`,
          },
          {
            id: "APP_A5",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_investment_interest,
            promptLatex: t("sm1_04.prompts.app_a5"),
            expressionLatex: "x + 0.05x = 2100",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xxxx"), expected: 2000, unit: "CHF" }],
            correctLatex: `x = 2000 \\text{ ${tObj.labels.currency}}`,
          },
        ],
        ELITE: [
          {
            id: "APP_E1",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_train_meeting,
            promptLatex: t("sm1_04.prompts.app_e1"),
            expressionLatex: "80x + 100x = 360",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.x"), expected: 2, unit: "hours" }],
            correctLatex: `x = 2 \\text{ ${tObj.labels.hours}}`,
          },
          {
            id: "APP_E2",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_age_ratio,
            promptLatex: t("sm1_04.prompts.app_e2"),
            expressionLatex: "\\frac{x + 5}{2x + 5} = \\frac{2}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 10, unit: "years" }],
            correctLatex: `x = 10 \\text{ ${tObj.labels.years}}`,
          },
          {
            id: "APP_E3",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_compound_mixture,
            promptLatex: t("sm1_04.prompts.app_e3"),
            expressionLatex: "x + 0.3 \\times 20 = 0.5(x + 20)",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 12, unit: "L" }],
            correctLatex: `x = 12 \\text{ ${tObj.labels.liters}}`,
          },
          {
            id: "APP_E4",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_boat_current,
            promptLatex: t("sm1_04.prompts.app_e4"),
            expressionLatex: "\\frac{30}{x + 2} + \\frac{30}{x - 2} = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xx"), expected: 10, unit: "km/h" }],
            correctLatex: `x = 10 \\text{ ${tObj.labels.speed_unit}}`,
          },
          {
            id: "APP_E5",
            difficulty,
            stage,
            scenario: tObj.scenarios.applications,
            context: tObj.problems.app_profit_loss,
            promptLatex: t("sm1_04.prompts.app_e5"),
            expressionLatex: "1.2x - 0.9x = 60",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: t("sm1_04.placeholders.xxx"), expected: 200, unit: "CHF" }],
            correctLatex: `x = 200 \\text{ ${tObj.labels.currency}}`,
          },
        ],
      },
    };

    return pools[stage][difficulty] || [];
  }, [t]);

  const buildPool = useCallback((difficulty: Difficulty, stage: Stage) => buildStagePool(sm1_04_t, difficulty, stage), [sm1_04_t, buildStagePool]);

  const {
    currentQuest: quest,
    stage,
    inputs,
    setInputs,
    lastCheck,
    verify,
    next,
    handleStageChange,
    difficulty,
    handleDifficultyChange,
    adaptiveRecommendation,
    aiFeedback,
    isRequestingAi,
    requestAiFeedback
  } = useQuestManager<EquationQuest, Stage>({
    moduleCode: "sm1-04",
    buildPool,
    initialStage: "BALANCE",
    tolerance: 0.01,
  });

  useEffect(() => {
    if (lastCheck?.ok) {
      completeStage("sm1-04", stage);
    }
  }, [lastCheck, completeStage, stage]);

  return (
    <ChamberLayout
      adaptiveRecommendation={adaptiveRecommendation}
      aiFeedback={aiFeedback}
      isRequestingAi={isRequestingAi}
      onAiDiagnosisRequested={requestAiFeedback}
      title={t("sm1_04.title")}
      moduleCode="SM1.04"
      difficulty={difficulty}
      onDifficultyChange={handleDifficultyChange}
      stages={[
        { id: "BALANCE", label: t("sm1_04.stages.balance") },
        { id: "SOLVE", label: t("sm1_04.stages.solve") },
        { id: "TRANSFORM", label: t("sm1_04.stages.transform") },
        { id: "APPLICATIONS", label: t("sm1_04.stages.applications") },
      ]}
      currentStage={stage}
      onStageChange={(s) => handleStageChange(s as Stage)}
      onVerify={verify}
      onNext={next}
      checkStatus={lastCheck}
      footerLeft={t("sm1_04.footer_left")}
      translations={{
        back: t("sm1_04.back"),
        check: t("sm1_04.check"),
        next: t("sm1_04.next"),
        correct: t("sm1_04.correct"),
        incorrect: t("sm1_04.incorrect"),
        ready: t("sm1_04.ready"),
        monitor_title: t("sm1_04.monitor_title"),
        difficulty: {
          basic: t("sm1_04.difficulty.basic"),
          core: t("sm1_04.difficulty.core"),
          advanced: t("sm1_04.difficulty.advanced"),
          elite: t("sm1_04.difficulty.elite"),
        },
      }}
      monitorContent={
        <div className="space-y-4">
          <EquationBalance
            stage={stage}
            quest={quest}
            translations={{
              left: sm1_04_t.labels.left,
              right: sm1_04_t.labels.right,
              operation: sm1_04_t.labels.operation,
              step1: sm1_04_t.labels.step1,
              step2: sm1_04_t.labels.step2,
              step3: sm1_04_t.labels.step3,
              bus: sm1_04_t.labels.bus,
              ferry: sm1_04_t.labels.ferry,
              apps: sm1_04_t.labels.apps,
              model: sm1_04_t.labels.model,
              steps_solve: sm1_04_t.labels.steps_solve,
              steps_trans: sm1_04_t.labels.steps_trans,
              problems: sm1_04_t.labels.problems
            }}
          />
        </div>
      }
    >
      <div className="space-y-8">
        {quest?.context && (
          <div className="p-6 bg-cyan-500/5 border border-cyan-500/20 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black mb-3">
              {t("sm1_04.scenario_title")}
            </div>
            <p className="text-white/80 leading-relaxed italic">{renderMixedText(quest.context)}</p>
          </div>
        )}

        {quest?.scenario && (
          <div className="p-6 bg-purple-500/10 border border-purple-500/30 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-purple-400 font-black mb-3">
              {t("sm1_04.basel_scenario")}
            </div>
            <p className="text-white/90 leading-relaxed font-medium">{renderMixedText(quest.scenario)}</p>
          </div>
        )}

        <div className="text-center space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white/60 font-black">
            {t("sm1_04.solve_title")}
          </div>
          <div className="text-3xl text-white font-black">
            {renderMixedText(quest?.promptLatex)}
          </div>
        </div>

        {quest?.expressionLatex && (
          <div className="text-center p-4 bg-white/5 border border-white/10 rounded-xl">
            <BlockMath math={quest.expressionLatex} />
          </div>
        )}

        <div className="max-w-md mx-auto space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white font-black text-center">
            {t("sm1_04.answer_title")}
          </div>
          {quest?.slots.map((slot) => (
            <div key={slot.id} className="space-y-2">
              <label className="text-sm text-white/70 font-mono">
                <InlineMath math={slot.labelLatex} />
              </label>
              <input
                value={inputs[slot.id] ?? ""}
                onChange={(e) => setInputs((prev) => ({ ...prev, [slot.id]: e.target.value }))}
                className="w-full bg-black border-2 border-cyan-500/50 p-4 text-center outline-none focus:border-cyan-400 placeholder:text-white/40 font-black text-2xl text-white rounded-lg"
                placeholder={slot.placeholder}
              />
            </div>
          ))}
        </div>

        {lastCheck?.ok && quest?.correctLatex && (
          <div className="text-center p-4 bg-green-500/10 border border-green-500/30 rounded-xl">
            <div className="text-green-400 font-black mb-2">{t("sm1_04.solution_title")}</div>
            <BlockMath math={quest.correctLatex} />
          </div>
        )}
      </div>
    </ChamberLayout>
  );
}
