"use client";

import { useEffect, useCallback } from "react";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";
import { useAppStore } from "@/lib/store";
import { translations } from "@/lib/i18n";
import ChamberLayout from "@/components/layout/ChamberLayout";
import EquationBalance from "@/components/chamber/sm1-05/EquationBalance";
import { Difficulty, Quest, useQuestManager } from "@/hooks/useQuestManager";

type Stage = "BALANCE" | "SOLVE" | "TRANSFORM" | "APPLICATIONS";
type EquationQuest = Quest & { 
  stage: Stage; 
  context?: string; 
  scenario?: string;
  equation?: string;
  leftSide?: number;
  rightSide?: number;
  operation?: string;
};

export default function SM105Page() {
  const { currentLanguage, completeStage } = useAppStore();
  const locale = translations[currentLanguage as keyof typeof translations] as typeof translations.EN;
  const t = locale.sm1_05 || translations.EN.sm1_05;

  const buildStagePool = useCallback((t: typeof translations.EN.sm1_05, difficulty: Difficulty, stage: Stage): EquationQuest[] => {
    const pools: Record<Stage, Record<Difficulty, EquationQuest[]>> = {
      BALANCE: {
        BASIC: [
          {
            id: "BAL_B1",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_add_both,
            promptLatex: "x + 3 = 7",
            expressionLatex: "x + 3 + 2 = 7 + 2",
            targetLatex: "x",
            equation: "x + 3 = 7",
            operation: "+2",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_B2",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_subtract_both,
            promptLatex: "x + 5 = 8",
            expressionLatex: "x + 5 - 5 = 8 - 5",
            targetLatex: "x",
            equation: "x + 5 = 8",
            operation: "-5",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_B3",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_multiply_both,
            promptLatex: "\\frac{x}{2} = 4",
            expressionLatex: "\\frac{x}{2} \\times 2 = 4 \\times 2",
            targetLatex: "x",
            equation: "x/2 = 4",
            operation: "×2",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "BAL_B4",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_divide_both,
            promptLatex: "2x = 10",
            expressionLatex: "\\frac{2x}{2} = \\frac{10}{2}",
            targetLatex: "x",
            equation: "2x = 10",
            operation: "÷2",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "BAL_B5",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_simple_check,
            promptLatex: "x + 2 = 6",
            expressionLatex: "x = 6 - 2",
            targetLatex: "x",
            equation: "x + 2 = 6",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        CORE: [
          {
            id: "BAL_C1",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_two_steps,
            promptLatex: "2x + 3 = 11",
            expressionLatex: "2x = 11 - 3, \\quad x = \\frac{8}{2}",
            targetLatex: "x",
            equation: "2x + 3 = 11",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_C2",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_negative_result,
            promptLatex: "x + 7 = 3",
            expressionLatex: "x = 3 - 7",
            targetLatex: "x",
            equation: "x + 7 = 3",
            slots: [{ id: "x", labelLatex: "x", placeholder: "-x", expected: -4, unit: "" }],
            correctLatex: "x = -4",
          },
          {
            id: "BAL_C3",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_fraction_coeff,
            promptLatex: "\\frac{x}{3} + 2 = 5",
            expressionLatex: "\\frac{x}{3} = 3, \\quad x = 9",
            targetLatex: "x",
            equation: "x/3 + 2 = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 9, unit: "" }],
            correctLatex: "x = 9",
          },
          {
            id: "BAL_C4",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_both_sides_x,
            promptLatex: "x + 5 = 2x",
            expressionLatex: "5 = 2x - x",
            targetLatex: "x",
            equation: "x + 5 = 2x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "BAL_C5",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_distribute,
            promptLatex: "3(x + 2) = 15",
            expressionLatex: "3x + 6 = 15, \\quad 3x = 9",
            targetLatex: "x",
            equation: "3(x + 2) = 15",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
        ],
        ADVANCED: [
          {
            id: "BAL_A1",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_complex_both,
            promptLatex: "2x + 3 = x + 7",
            expressionLatex: "2x - x = 7 - 3",
            targetLatex: "x",
            equation: "2x + 3 = x + 7",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "BAL_A2",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_fractions,
            promptLatex: "\\frac{x}{2} + \\frac{x}{3} = 5",
            expressionLatex: "\\frac{3x + 2x}{6} = 5, \\quad 5x = 30",
            targetLatex: "x",
            equation: "x/2 + x/3 = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "BAL_A3",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_parentheses_both,
            promptLatex: "2(x + 1) = 3(x - 2)",
            expressionLatex: "2x + 2 = 3x - 6, \\quad x = 8",
            targetLatex: "x",
            equation: "2(x + 1) = 3(x - 2)",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "BAL_A4",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_decimal_coeff,
            promptLatex: "0.5x + 1.5 = 3",
            expressionLatex: "0.5x = 1.5, \\quad x = 3",
            targetLatex: "x",
            equation: "0.5x + 1.5 = 3",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_A5",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_negative_coeff,
            promptLatex: "-2x + 5 = -3",
            expressionLatex: "-2x = -8, \\quad x = 4",
            targetLatex: "x",
            equation: "-2x + 5 = -3",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        ELITE: [
          {
            id: "BAL_E1",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_nested_parens,
            promptLatex: "2(3x - (x + 1)) = 10",
            expressionLatex: "2(2x - 1) = 10, \\quad 4x - 2 = 10",
            targetLatex: "x",
            equation: "2(3x - (x + 1)) = 10",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "BAL_E2",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_three_fractions,
            promptLatex: "\\frac{x}{2} - \\frac{x}{3} + \\frac{x}{6} = 2",
            expressionLatex: "\\frac{3x - 2x + x}{6} = 2, \\quad 2x = 12",
            targetLatex: "x",
            equation: "x/2 - x/3 + x/6 = 2",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "BAL_E3",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_complex_distribute,
            promptLatex: "3(2x - 1) - 2(x + 3) = 5",
            expressionLatex: "6x - 3 - 2x - 6 = 5, \\quad 4x = 14",
            targetLatex: "x",
            equation: "3(2x - 1) - 2(x + 3) = 5",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.x", expected: 3.5, unit: "" }],
            correctLatex: "x = 3.5",
          },
          {
            id: "BAL_E4",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_reciprocal,
            promptLatex: "\\frac{1}{x} + \\frac{1}{2x} = \\frac{3}{4}",
            expressionLatex: "\\frac{2 + 1}{2x} = \\frac{3}{4}, \\quad x = 2",
            targetLatex: "x",
            equation: "1/x + 1/(2x) = 3/4",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 2, unit: "" }],
            correctLatex: "x = 2",
          },
          {
            id: "BAL_E5",
            difficulty,
            stage,
            scenario: t.scenarios.balance,
            context: t.problems.bal_proportion,
            promptLatex: "\\frac{x + 1}{x - 1} = 2",
            expressionLatex: "x + 1 = 2(x - 1), \\quad x = 3",
            targetLatex: "x",
            equation: "(x + 1)/(x - 1) = 2",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
        ],
      },
      SOLVE: {
        BASIC: [
          {
            id: "SOL_B1",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_one_step_add,
            promptLatex: "x + 3 = 7",
            expressionLatex: "x = 7 - 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_B2",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_one_step_sub,
            promptLatex: "x - 5 = 2",
            expressionLatex: "x = 2 + 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 7, unit: "" }],
            correctLatex: "x = 7",
          },
          {
            id: "SOL_B3",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_one_step_mult,
            promptLatex: "3x = 12",
            expressionLatex: "x = \\frac{12}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_B4",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_one_step_div,
            promptLatex: "\\frac{x}{4} = 3",
            expressionLatex: "x = 3 \\times 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "SOL_B5",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_negative_simple,
            promptLatex: "x + 8 = 3",
            expressionLatex: "x = 3 - 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "-x", expected: -5, unit: "" }],
            correctLatex: "x = -5",
          },
        ],
        CORE: [
          {
            id: "SOL_C1",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_two_step_1,
            promptLatex: "2x + 5 = 13",
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_C2",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_two_step_2,
            promptLatex: "\\frac{x}{3} - 2 = 4",
            expressionLatex: "\\frac{x}{3} = 6, \\quad x = 18",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 18, unit: "" }],
            correctLatex: "x = 18",
          },
          {
            id: "SOL_C3",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_negative_coeff,
            promptLatex: "-3x = 15",
            expressionLatex: "x = \\frac{15}{-3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "-x", expected: -5, unit: "" }],
            correctLatex: "x = -5",
          },
          {
            id: "SOL_C4",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_fraction_result,
            promptLatex: "2x + 1 = 4",
            expressionLatex: "2x = 3, \\quad x = 1.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.x", expected: 1.5, unit: "" }],
            correctLatex: "x = 1.5",
          },
          {
            id: "SOL_C5",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_decimal_coeff,
            promptLatex: "0.5x = 4",
            expressionLatex: "x = \\frac{4}{0.5}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
        ],
        ADVANCED: [
          {
            id: "SOL_A1",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_combine_like,
            promptLatex: "3x + 2x - 4 = 11",
            expressionLatex: "5x = 15, \\quad x = 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "SOL_A2",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_distribute_simple,
            promptLatex: "2(x + 3) = 14",
            expressionLatex: "2x + 6 = 14, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_A3",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_x_both_sides,
            promptLatex: "5x - 2 = 3x + 6",
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_A4",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_fraction_both,
            promptLatex: "\\frac{x}{2} + \\frac{x}{4} = 6",
            expressionLatex: "\\frac{3x}{4} = 6, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "SOL_A5",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_negative_both,
            promptLatex: "-2x + 3 = -x - 5",
            expressionLatex: "-x = -8, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
        ],
        ELITE: [
          {
            id: "SOL_E1",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_complex_distribute,
            promptLatex: "3(2x - 1) = 2(x + 5)",
            expressionLatex: "6x - 3 = 2x + 10, \\quad x = 3.25",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.xx", expected: 3.25, unit: "" }],
            correctLatex: "x = 3.25",
          },
          {
            id: "SOL_E2",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_nested_parens,
            promptLatex: "2(x - (3 - x)) = 10",
            expressionLatex: "2(2x - 3) = 10, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "SOL_E3",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_three_terms,
            promptLatex: "\\frac{x}{2} + \\frac{x}{3} - \\frac{x}{6} = 4",
            expressionLatex: "\\frac{2x}{3} = 4, \\quad x = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "SOL_E4",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_decimal_complex,
            promptLatex: "0.3x + 0.5(x - 2) = 2.6",
            expressionLatex: "0.8x - 1 = 2.6, \\quad x = 4.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.x", expected: 4.5, unit: "" }],
            correctLatex: "x = 4.5",
          },
          {
            id: "SOL_E5",
            difficulty,
            stage,
            scenario: t.scenarios.solve,
            context: t.problems.sol_proportion_eq,
            promptLatex: "\\frac{x - 2}{3} = \\frac{x + 1}{5}",
            expressionLatex: "5(x - 2) = 3(x + 1), \\quad x = 6.5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.x", expected: 6.5, unit: "" }],
            correctLatex: "x = 6.5",
          },
        ],
      },
      TRANSFORM: {
        BASIC: [
          {
            id: "TRA_B1",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_move_constant,
            promptLatex: "x + 7 = 12",
            expressionLatex: "x = 12 - 7",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B2",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_move_variable,
            promptLatex: "2x = x + 5",
            expressionLatex: "2x - x = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B3",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_isolate_x,
            promptLatex: "3x = 15",
            expressionLatex: "x = \\frac{15}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_B4",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_two_moves,
            promptLatex: "2x + 3 = 11",
            expressionLatex: "2x = 8, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_B5",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_negative_move,
            promptLatex: "x - 6 = -2",
            expressionLatex: "x = -2 + 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        CORE: [
          {
            id: "TRA_C1",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_collect_terms,
            promptLatex: "3x + 2x = 20",
            expressionLatex: "5x = 20, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C2",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_move_both,
            promptLatex: "4x + 3 = 2x + 11",
            expressionLatex: "4x - 2x = 11 - 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C3",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_expand_first,
            promptLatex: "2(x + 3) = 14",
            expressionLatex: "2x + 6 = 14, \\quad x = 4",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
          {
            id: "TRA_C4",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_fraction_clear,
            promptLatex: "\\frac{x}{3} + 2 = 5",
            expressionLatex: "\\frac{x}{3} = 3, \\quad x = 9",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 9, unit: "" }],
            correctLatex: "x = 9",
          },
          {
            id: "TRA_C5",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_negative_coeff,
            promptLatex: "-2x + 5 = 1",
            expressionLatex: "-2x = -4, \\quad x = 2",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 2, unit: "" }],
            correctLatex: "x = 2",
          },
        ],
        ADVANCED: [
          {
            id: "TRA_A1",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_multi_step,
            promptLatex: "3(x - 2) + 2x = 19",
            expressionLatex: "3x - 6 + 2x = 19, \\quad 5x = 25",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_A2",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_both_expand,
            promptLatex: "2(x + 1) = 3(x - 2)",
            expressionLatex: "2x + 2 = 3x - 6, \\quad x = 8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 8, unit: "" }],
            correctLatex: "x = 8",
          },
          {
            id: "TRA_A3",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_fractions_lcd,
            promptLatex: "\\frac{x}{2} + \\frac{x}{3} = 10",
            expressionLatex: "\\frac{5x}{6} = 10, \\quad x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "TRA_A4",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_decimal_expand,
            promptLatex: "0.5(x + 4) = 3.5",
            expressionLatex: "0.5x + 2 = 3.5, \\quad x = 3",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "" }],
            correctLatex: "x = 3",
          },
          {
            id: "TRA_A5",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_complex_collect,
            promptLatex: "5x - 2(x - 3) = 18",
            expressionLatex: "5x - 2x + 6 = 18, \\quad 3x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 4, unit: "" }],
            correctLatex: "x = 4",
          },
        ],
        ELITE: [
          {
            id: "TRA_E1",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_nested_complex,
            promptLatex: "3(2x - (x + 1)) = 15",
            expressionLatex: "3(x - 1) = 15, \\quad x = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 6, unit: "" }],
            correctLatex: "x = 6",
          },
          {
            id: "TRA_E2",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_three_fractions,
            promptLatex: "\\frac{x}{2} - \\frac{x}{3} + \\frac{x}{4} = 5",
            expressionLatex: "\\frac{5x}{12} = 5, \\quad x = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 12, unit: "" }],
            correctLatex: "x = 12",
          },
          {
            id: "TRA_E3",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_double_expand,
            promptLatex: "2(3x - 1) - 3(x + 2) = 7",
            expressionLatex: "6x - 2 - 3x - 6 = 7, \\quad 3x = 15",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "" }],
            correctLatex: "x = 5",
          },
          {
            id: "TRA_E4",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_proportion_cross,
            promptLatex: "\\frac{2x + 1}{3} = \\frac{x - 2}{2}",
            expressionLatex: "2(2x + 1) = 3(x - 2), \\quad x = -8",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "-x", expected: -8, unit: "" }],
            correctLatex: "x = -8",
          },
          {
            id: "TRA_E5",
            difficulty,
            stage,
            scenario: t.scenarios.transform,
            context: t.problems.tra_mixed_complex,
            promptLatex: "0.5(4x - 2) + \\frac{x}{3} = 7",
            expressionLatex: "2x - 1 + \\frac{x}{3} = 7, \\quad x = 3.6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x.x", expected: 3.6, unit: "" }],
            correctLatex: "x = 3.6",
          },
        ],
      },
      APPLICATIONS: {
        BASIC: [
          {
            id: "APP_B1",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_bus_ticket,
            promptLatex: "\\text{Ticket price}",
            expressionLatex: "x + 2 = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "CHF" }],
            correctLatex: "x = 3 \\text{ CHF}",
          },
          {
            id: "APP_B2",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_rhine_time,
            promptLatex: "\\text{Ferry time}",
            expressionLatex: "2x = 10",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 5, unit: "min" }],
            correctLatex: "x = 5 \\text{ min}",
          },
          {
            id: "APP_B3",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_age_simple,
            promptLatex: "\\text{Age}",
            expressionLatex: "x + 5 = 12",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 7, unit: "years" }],
            correctLatex: "x = 7 \\text{ years}",
          },
          {
            id: "APP_B4",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_distance_simple,
            promptLatex: "\\text{Distance}",
            expressionLatex: "\\frac{x}{2} = 6",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 12, unit: "km" }],
            correctLatex: "x = 12 \\text{ km}",
          },
          {
            id: "APP_B5",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_price_discount,
            promptLatex: "\\text{Original price}",
            expressionLatex: "x - 10 = 40",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 50, unit: "CHF" }],
            correctLatex: "x = 50 \\text{ CHF}",
          },
        ],
        CORE: [
          {
            id: "APP_C1",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_tram_tickets,
            promptLatex: "\\text{Adult tickets}",
            expressionLatex: "3x + 2 \\times 2 = 13",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "CHF" }],
            correctLatex: "x = 3 \\text{ CHF}",
          },
          {
            id: "APP_C2",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_novartis_samples,
            promptLatex: "\\text{Samples per box}",
            expressionLatex: "5x + 10 = 60",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 10, unit: "" }],
            correctLatex: "x = 10 \\text{ samples}",
          },
          {
            id: "APP_C3",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_age_sum,
            promptLatex: "\\text{Son's age}",
            expressionLatex: "x + (x + 30) = 50",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 10, unit: "years" }],
            correctLatex: "x = 10 \\text{ years}",
          },
          {
            id: "APP_C4",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_rectangle_perimeter,
            promptLatex: "\\text{Width}",
            expressionLatex: "2(x + 8) = 28",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 6, unit: "m" }],
            correctLatex: "x = 6 \\text{ m}",
          },
          {
            id: "APP_C5",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_speed_distance,
            promptLatex: "\\text{Speed}",
            expressionLatex: "2x = 80",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 40, unit: "km/h" }],
            correctLatex: "x = 40 \\text{ km/h}",
          },
        ],
        ADVANCED: [
          {
            id: "APP_A1",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_roche_concentration,
            promptLatex: "\\text{Original concentration}",
            expressionLatex: "0.5x + 0.3 \\times 100 = 0.4 \\times 150",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 60, unit: "%" }],
            correctLatex: "x = 60\\%",
          },
          {
            id: "APP_A2",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_consecutive_numbers,
            promptLatex: "\\text{First number}",
            expressionLatex: "x + (x + 1) + (x + 2) = 48",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 15, unit: "" }],
            correctLatex: "x = 15",
          },
          {
            id: "APP_A3",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_work_rate,
            promptLatex: "\\text{Hours for worker A}",
            expressionLatex: "\\frac{1}{x} + \\frac{1}{6} = \\frac{1}{2}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 3, unit: "hours" }],
            correctLatex: "x = 3 \\text{ hours}",
          },
          {
            id: "APP_A4",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_mixture_problem,
            promptLatex: "\\text{Liters of 20% solution}",
            expressionLatex: "0.2x + 0.5 \\times 10 = 0.3(x + 10)",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 20, unit: "L" }],
            correctLatex: "x = 20 \\text{ L}",
          },
          {
            id: "APP_A5",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_investment_interest,
            promptLatex: "\\text{Principal amount}",
            expressionLatex: "x + 0.05x = 2100",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xxxx", expected: 2000, unit: "CHF" }],
            correctLatex: "x = 2000 \\text{ CHF}",
          },
        ],
        ELITE: [
          {
            id: "APP_E1",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_train_meeting,
            promptLatex: "\\text{Time to meet}",
            expressionLatex: "80x + 100x = 360",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "x", expected: 2, unit: "hours" }],
            correctLatex: "x = 2 \\text{ hours}",
          },
          {
            id: "APP_E2",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_age_ratio,
            promptLatex: "\\text{Current age}",
            expressionLatex: "\\frac{x + 5}{2x + 5} = \\frac{2}{3}",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 10, unit: "years" }],
            correctLatex: "x = 10 \\text{ years}",
          },
          {
            id: "APP_E3",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_compound_mixture,
            promptLatex: "\\text{Amount of pure acid}",
            expressionLatex: "x + 0.3 \\times 20 = 0.5(x + 20)",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 12, unit: "L" }],
            correctLatex: "x = 12 \\text{ L}",
          },
          {
            id: "APP_E4",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_boat_current,
            promptLatex: "\\text{Boat speed in still water}",
            expressionLatex: "\\frac{30}{x + 2} + \\frac{30}{x - 2} = 5",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xx", expected: 10, unit: "km/h" }],
            correctLatex: "x = 10 \\text{ km/h}",
          },
          {
            id: "APP_E5",
            difficulty,
            stage,
            scenario: t.scenarios.applications,
            context: t.problems.app_profit_loss,
            promptLatex: "\\text{Cost price}",
            expressionLatex: "1.2x - 0.9x = 60",
            targetLatex: "x",
            slots: [{ id: "x", labelLatex: "x", placeholder: "xxx", expected: 200, unit: "CHF" }],
            correctLatex: "x = 200 \\text{ CHF}",
          },
        ],
      },
    };

    return pools[stage][difficulty] || [];
  }, []);

  const buildPool = useCallback((difficulty: Difficulty, stage: Stage) => buildStagePool(t, difficulty, stage), [t, buildStagePool]);

  const {
    currentQuest: quest,
    stage,
    inputs,
    setInputs,
    lastCheck,
    verify,
    next,
    handleStageChange,
    difficulty,
    handleDifficultyChange,
  } = useQuestManager<EquationQuest, Stage>({
    buildPool,
    initialStage: "BALANCE",
    tolerance: 0.01,
  });

  useEffect(() => {
    if (lastCheck?.ok) {
      completeStage("sm1-05", stage);
    }
  }, [lastCheck, completeStage, stage]);

  return (
    <ChamberLayout
      title={t.title}
      moduleCode="SM1.05"
      difficulty={difficulty}
      onDifficultyChange={handleDifficultyChange}
      stages={[
        { id: "BALANCE", label: t.stages.balance },
        { id: "SOLVE", label: t.stages.solve },
        { id: "TRANSFORM", label: t.stages.transform },
        { id: "APPLICATIONS", label: t.stages.applications },
      ]}
      currentStage={stage}
      onStageChange={(s) => handleStageChange(s as Stage)}
      onVerify={verify}
      onNext={next}
      checkStatus={lastCheck}
      footerLeft={t.footer_left}
      translations={{
        back: t.back,
        check: t.check,
        next: t.next,
        correct: t.correct,
        incorrect: t.incorrect,
        ready: t.ready,
        monitor_title: t.monitor_title,
        difficulty: {
          basic: t.difficulty.basic,
          core: t.difficulty.core,
          advanced: t.difficulty.advanced,
          elite: t.difficulty.elite,
        },
      }}
      monitorContent={
        <div className="space-y-4">
          <EquationBalance 
            stage={stage} 
            quest={quest}
            language={currentLanguage as "EN" | "CN" | "DE"} 
          />
        </div>
      }
    >
      <div className="space-y-8">
        {quest?.scenario && (
          <div className="p-6 bg-purple-500/10 border border-purple-500/30 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-purple-400 font-black mb-3">
              {t.basel_scenario}
            </div>
            <p className="text-white/90 leading-relaxed font-medium">{quest.scenario}</p>
          </div>
        )}

        {quest?.context && (
          <div className="p-6 bg-cyan-500/5 border border-cyan-500/20 rounded-xl">
            <div className="text-[10px] uppercase tracking-[0.4em] text-cyan-400 font-black mb-3">
              {t.scenario_title}
            </div>
            <p className="text-white/80 leading-relaxed">{quest.context}</p>
          </div>
        )}

        <div className="text-center space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white/60 font-black">
            {t.solve_title}
          </div>
          <div className="text-3xl text-white font-black">
            <InlineMath math={quest?.promptLatex || ""} />
          </div>
        </div>

        {quest?.expressionLatex && (
          <div className="text-center p-4 bg-white/5 border border-white/10 rounded-xl">
            <BlockMath math={quest.expressionLatex} />
          </div>
        )}

        <div className="max-w-md mx-auto space-y-4">
          <div className="text-[10px] uppercase tracking-[0.4em] text-white font-black text-center">
            {t.answer_title}
          </div>
          {quest?.slots.map((slot) => (
            <div key={slot.id} className="space-y-2">
              <label className="text-sm text-white/70 font-mono">
                <InlineMath math={slot.labelLatex} />
              </label>
              <input
                value={inputs[slot.id] ?? ""}
                onChange={(e) => setInputs((prev) => ({ ...prev, [slot.id]: e.target.value }))}
                className="w-full bg-black border-2 border-cyan-500/50 p-4 text-center outline-none focus:border-cyan-400 placeholder:text-white/40 font-black text-2xl text-white rounded-lg"
                placeholder={slot.placeholder}
              />
            </div>
          ))}
        </div>

        {lastCheck?.ok && quest?.correctLatex && (
          <div className="text-center p-4 bg-green-500/10 border border-green-500/30 rounded-xl">
            <div className="text-green-400 font-black mb-2">{t.solution_title}</div>
            <BlockMath math={quest.correctLatex} />
          </div>
        )}
      </div>
    </ChamberLayout>
  );
}
